"""Regenerate coop_mod/sndcache.scr - per-map deterministic slice of the death-voice pool.

WHY (load-time research, 2026-08-05): the old list forced all 695 pool wavs on ALL 55 maps. Each
forced cache allocates a sound CONFIGSTRING pushed to every client, so coop was sitting at
1,585 of 1,600 MAX_SOUNDS - fifteen slots from a hard gi.Error(ERR_DROP) - and paying ~0.7-1.0 s
of post-spawn hitch plus ~424 extra reliable configstrings on every remote client (the thing that
made sweep clients miss the rotation).

WHAT CHANGES: nothing ships differently and no alias table shrinks - ubersound/coop_deathvox.scr
still registers every alias, so any line can still play. Only the forced PRECACHE list is sliced:
the 484 interchangeable death grunts become a deterministic per-map window of DEATHVOX_PER_MAP,
selected by a hash of the map name so a given map always caches the same subset (reproducible,
and different maps draw different voices). The small character pools (flvo / gurgle / headshot,
149 files) stay fully cached - they are specific sounds, not interchangeable variants.

Usage:  python _research/gen_sndcache.py            # rewrites coop_mod/sndcache.scr
"""
import os, re, io, glob
import sys

# ============================================================================================
# [user 2026-08-10] OBSOLETE - DO NOT RUN WITHOUT READING THIS.
#
# deathvox, flvo, gurgle and headshot are no longer precached through this script. They are now
# declared with `aliascache` in ubersound/, which precaches inside CG_RegisterSounds during
# CA_LOADING - behind the loading screen, at ZERO configstrings and zero network traffic.
#
# That removes the problem this generator was written to work around. Its own header records
# coop sitting at 1585/1600 MAX_SOUNDS, fifteen slots from a hard ERR_DROP, which is why death
# voices were sliced to a per-map window of 60 out of 484. The aliascache migration freed 633
# server sound-index slots outright, so the slicing is no longer needed and every death voice is
# available on every map again.
#
# This script would also now FAIL: it derives its file list by re-reading the previous
# sndcache.scr and asserts that deathvox entries are present. Those lines are gone.
#
# If you ever need to regenerate the remaining 62 sound/dialogue/ caches, source the list from the
# ubersound alias files rather than from the previous output, and do NOT re-add any directory that
# is aliascache-owned (coop_deathvox, coop_flvo, coop_gurgle, coop_headshot).
# ============================================================================================
sys.exit("gen_sndcache.py is obsolete - see the header. deathvox/flvo/gurgle/headshot are now aliascache-precached in ubersound/, and this script would re-add them AND fail its own assert.")


HERE = os.path.dirname(os.path.abspath(__file__))
MOD = os.path.dirname(HERE)
OUT = os.path.join(MOD, "coop_mod", "sndcache.scr")
DEATHVOX_PER_MAP = 60          # of 484; tune here

old = io.open(OUT, encoding="latin-1").read()
files = re.findall(r"cache (sound/\S+\.wav)", old)
deathvox = sorted(f for f in files if "/coop_deathvox/" in f)
keep_all = [f for f in files if "/coop_deathvox/" not in f]
assert deathvox and keep_all, "unexpected sndcache content"

maps = sorted({os.path.basename(p)[:-4].lower()
               for p in glob.glob(os.path.join(MOD, "maps", "*.scr"))
               if re.match(r"^[mte]\d", os.path.basename(p))})

L = []
L.append("// HZM coop - voice-pool precache (bug-1141 lag spikes). GENERATED by")
L.append("// _research/gen_sndcache.py - do not hand-edit.")
L.append("//")
L.append("// [2026-08-05] PER-MAP SLICE. Forcing all 695 pool wavs on all 55 maps put coop at")
L.append("// 1585/1600 MAX_SOUNDS (15 slots from a hard ERR_DROP) and cost ~1s of post-spawn hitch")
L.append("// plus ~424 reliable configstrings on every client. The character pools below are still")
L.append("// cached in full; the 484 interchangeable death grunts are now a deterministic per-map")
L.append("// window of %d, chosen by map name. Every alias still exists in" % DEATHVOX_PER_MAP)
L.append("// ubersound/coop_deathvox.scr, so any line can still play - only the precache is sliced.")
L.append("main:{")
for f in keep_all:
    L.append("\tcache %s" % f)
L.append("")
L.append("\t//deterministic per-map death-voice window")
L.append("\tlocal.m = level.coop_mapname")
for i, mp in enumerate(maps):
    start = (i * 37) % max(1, len(deathvox) - DEATHVOX_PER_MAP)
    sl = deathvox[start:start + DEATHVOX_PER_MAP]
    L.append('\tif( local.m == "%s" ){' % mp)
    for f in sl:
        L.append("\t\tcache %s" % f)
    L.append("\t}")
L.append("")
L.append("\t//fallback for any map not listed above")
L.append("\tif( local.m == NIL || local.m == \"\" ){")
for f in deathvox[:DEATHVOX_PER_MAP]:
    L.append("\t\tcache %s" % f)
L.append("\t}")
L.append("}end")

io.open(OUT, "w", newline="\n").write("\n".join(L) + "\n")
kept = len(keep_all) + DEATHVOX_PER_MAP
print("sndcache.scr regenerated: %d forced caches per map (was %d) - frees %d sound slots"
      % (kept, len(files), len(files) - kept))
print("maps covered: %d" % len(maps))
