junk
{
	qer_editorimage textures/junk.tga
	{
		map textures/junk.tga
		rgbGen lightingSpherical
	}
}
17thairb_assaultvestbloody
{
	qer_editorimage textures/17thairb_assaultvestbloody.tga
	{
		map textures/17thairb_assaultvestbloody.tga
		rgbGen lightingSpherical
	}
}
17thairb_pantsv12b
{
	qer_editorimage textures/17thairb_pantsbootsv12b.tga
	{
		map textures/17thairb_pantsbootsv12b.tga
		rgbGen lightingSpherical
	}
}
17thairb_army_sfcv12
{
	qer_editorimage textures/17thairb_army_sfcv12.tga
	{
		map textures/17thairb_army_sfcv12.tga
		rgbGen lightingSpherical
	}
}
17thairb_helmet_shots
{
	qer_editorimage textures/17thairb_helmet_shots.tga
	cull none
	{
		map textures/17thairb_helmet_shots.tga
		rgbGen lightingSpherical
	}
}
handsbloody
{
	qer_editorimage textures/handsbloody.tga
	{
		map textures/handsbloody.tga
		rgbGen lightingSpherical
	}
}