1st_sniper_viewsleeves
{
	qer_editorimage textures/1st_sniper_viewsleeves.tga
	{
		map textures/1st_sniper_viewsleeves.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_handview
{
	qer_editorimage textures/1st_sniper_handview.tga
	{
		map textures/1st_sniper_handview.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_hand
{
	qer_editorimage textures/1st_sniper_hand.tga
	{
		map textures/1st_sniper_hand.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_slick
{
	qer_editorimage textures/1st_sniper_slick.tga
	{
		map textures/1st_sniper_slick.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_top
{
	qer_editorimage textures/1st_assaultvest_sniper.tga
	{
		map textures/1st_assaultvest_sniper.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_pants
{
	qer_editorimage textures/1st_sniper_pants.tga
	{
		map textures/1st_sniper_pants.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_helm
{
	qer_editorimage textures/1st_sniper_helm.tga
	cull none
	{
		map textures/1st_sniper_helm.tga
		rgbGen lightingSpherical
	}
}

1st_sniper_armband
{
	qer_editorimage textures/1st__sniper_armband.tga
	{
		map textures/1st_sniper_armband.tga
		rgbGen lightingSpherical
	}
}

