// HZM coop [user 2026-09-27] LOOPING LOADING MEDAL (design v4) - GENERATED by docs/tools/gen_loadscreen_medal.py
// --morph --speed 45 --period 16. Do not hand-edit: regenerate. Old <-> new, forever, the whole logo turning
// rigidly at 45 deg/s; 16 s per full cycle (2 revolution(s)). Every stage shares the tcMod rotate (one angle),
// oldest on top, each fading once per cycle (clamped-sine alphaGen wave, phase 0.25 = peak at the old state).
hzmLoadMedalMorph
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap ui/hzm_loadscreen/morph_modern.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
	}
	{
		clampMap ui/hzm_loadscreen/morph_l4.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
		alphaGen wave sin 2.4928 2.9111 0.25 0.0625
	}
	{
		clampMap ui/hzm_loadscreen/morph_l3.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
		alphaGen wave sin 1.3402 2.2823 0.25 0.0625
	}
	{
		clampMap ui/hzm_loadscreen/morph_l2.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
		alphaGen wave sin 0.5000 2.1221 0.25 0.0625
	}
	{
		clampMap ui/hzm_loadscreen/morph_l1.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
		alphaGen wave sin -0.3402 2.2823 0.25 0.0625
	}
	{
		clampMap ui/hzm_loadscreen/morph_l0.tga
		blendFunc GL_SRC_ALPHA GL_ONE_MINUS_SRC_ALPHA
		tcMod rotate 45
		alphaGen wave sin -1.4928 2.9111 0.25 0.0625
	}
}
