// HZM coop - GORE TIER 1 (damage-tier blood skins), SECOND PASS.
// GENERATED by docs/tools/gen_gore_skins.py - do not hand-edit, re-run the generator.
// Companion to scripts/coop_gore.shader, whose original generator was lost in a session
// scratchpad; this one lives in the repo and has a --check mode so that cannot recur.
// Each block is the model's ORIGINAL surface shader body, retargeted at a composited
// diffuse whose blood pixels are the mod's authority colours #150200 fresh / (7,1,0)
// dried. Coverage and alpha are matched to the already-shipped skins by measurement.

adhelm_blood1
{
	qer_editorimage textures/models/human/faces/adhelm_blood1.jpg
	
	{
		map textures/models/human/faces/adhelm_blood1.jpg
		rgbGen lightingSpherical
	}

}

adhelm_blood2
{
	qer_editorimage textures/models/human/faces/adhelm_blood2.jpg
	
	{
		map textures/models/human/faces/adhelm_blood2.jpg
		rgbGen lightingSpherical
	}

}

adhelm_blood3
{
	qer_editorimage textures/models/human/faces/adhelm_blood3.jpg
	
	{
		map textures/models/human/faces/adhelm_blood3.jpg
		rgbGen lightingSpherical
	}

}

af_p_glasses_blood1
{
	cull none
	qer_editorimage textures/models/equipment/Af_P_Glasses_blood1.jpg
	{
		map textures/models/equipment/Af_P_Glasses_blood1.jpg
		rgbGen lightingSpherical


	}

}

af_p_glasses_blood2
{
	cull none
	qer_editorimage textures/models/equipment/Af_P_Glasses_blood2.jpg
	{
		map textures/models/equipment/Af_P_Glasses_blood2.jpg
		rgbGen lightingSpherical


	}

}

af_p_glasses_blood3
{
	cull none
	qer_editorimage textures/models/equipment/Af_P_Glasses_blood3.jpg
	{
		map textures/models/equipment/Af_P_Glasses_blood3.jpg
		rgbGen lightingSpherical


	}

}

af_p_glasses_reflection_blood1
{
	{
		map textures/common/Af_P_Glasses_reflection_blood1.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel


	}

}

af_p_glasses_reflection_blood2
{
	{
		map textures/common/Af_P_Glasses_reflection_blood2.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel


	}

}

af_p_glasses_reflection_blood3
{
	{
		map textures/common/Af_P_Glasses_reflection_blood3.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel


	}

}

al_us_mask_blood1
{
	qer_editorimage textures/models/human/faces/AL_US_Mask_blood1.jpg
	{
		map textures/models/human/faces/AL_US_Mask_blood1.jpg
		rgbGen lightingSpherical
	}

}

al_us_mask_blood2
{
	qer_editorimage textures/models/human/faces/AL_US_Mask_blood2.jpg
	{
		map textures/models/human/faces/AL_US_Mask_blood2.jpg
		rgbGen lightingSpherical
	}

}

al_us_mask_blood3
{
	qer_editorimage textures/models/human/faces/AL_US_Mask_blood3.jpg
	{
		map textures/models/human/faces/AL_US_Mask_blood3.jpg
		rgbGen lightingSpherical
	}

}

al_us_maskhead_blood1
{
	qer_editorimage textures/models/human/faces/AL_US_MaskHead_blood1.jpg
	{
		map textures/models/human/faces/AL_US_MaskHead_blood1.jpg
		rgbGen lightingSpherical
	}

}

al_us_maskhead_blood2
{
	qer_editorimage textures/models/human/faces/AL_US_MaskHead_blood2.jpg
	{
		map textures/models/human/faces/AL_US_MaskHead_blood2.jpg
		rgbGen lightingSpherical
	}

}

al_us_maskhead_blood3
{
	qer_editorimage textures/models/human/faces/AL_US_MaskHead_blood3.jpg
	{
		map textures/models/human/faces/AL_US_MaskHead_blood3.jpg
		rgbGen lightingSpherical
	}

}

al_us_tankhat_blood1
{
        qer_editorimage textures/models/equipment/Sc_AL_US_Tank_Hat_blood1.jpg
        cull none
	{
		map textures/models/equipment/Sc_AL_US_Tank_Hat_blood1.jpg
               	rgbGen lightingSpherical
	}

}

al_us_tankhat_blood2
{
        qer_editorimage textures/models/equipment/Sc_AL_US_Tank_Hat_blood2.jpg
        cull none
	{
		map textures/models/equipment/Sc_AL_US_Tank_Hat_blood2.jpg
               	rgbGen lightingSpherical
	}

}

al_us_tankhat_blood3
{
        qer_editorimage textures/models/equipment/Sc_AL_US_Tank_Hat_blood3.jpg
        cull none
	{
		map textures/models/equipment/Sc_AL_US_Tank_Hat_blood3.jpg
               	rgbGen lightingSpherical
	}

}

atank_blood1
{
	qer_editorimage textures/models/human/faces/Atank_blood1.jpg
	
	{
		map textures/models/human/faces/Atank_blood1.jpg
		rgbGen lightingSpherical
	}

}

atank_blood2
{
	qer_editorimage textures/models/human/faces/Atank_blood2.jpg
	
	{
		map textures/models/human/faces/Atank_blood2.jpg
		rgbGen lightingSpherical
	}

}

atank_blood3
{
	qer_editorimage textures/models/human/faces/Atank_blood3.jpg
	
	{
		map textures/models/human/faces/Atank_blood3.jpg
		rgbGen lightingSpherical
	}

}

bignose_blood1
{
	qer_editorimage textures/models/human/faces/bignose_blood1.jpg
	{
		map textures/models/human/faces/bignose_blood1.jpg
		rgbGen lightingSpherical
	}

}

bignose_blood2
{
	qer_editorimage textures/models/human/faces/bignose_blood2.jpg
	{
		map textures/models/human/faces/bignose_blood2.jpg
		rgbGen lightingSpherical
	}

}

bjorn_blood1
{
	qer_editorimage textures/models/human/faces/bjorn_blood1.jpg
	
	{
		map textures/models/human/faces/bjorn_blood1.jpg
		rgbGen lightingSpherical
	}

}

bjorn_blood2
{
	qer_editorimage textures/models/human/faces/bjorn_blood2.jpg
	
	{
		map textures/models/human/faces/bjorn_blood2.jpg
		rgbGen lightingSpherical
	}

}

bjorn_blood3
{
	qer_editorimage textures/models/human/faces/bjorn_blood3.jpg
	
	{
		map textures/models/human/faces/bjorn_blood3.jpg
		rgbGen lightingSpherical
	}

}

c_manon_shirt_blood3
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood3.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood3.jpg
		rgbGen lightingSpherical
	}

}

claus_blood1
{
	qer_editorimage textures/models/human/faces/claus_blood1.jpg
	
	{
		map textures/models/human/faces/claus_blood1.jpg
		rgbGen lightingSpherical
	}

}

claus_blood2
{
	qer_editorimage textures/models/human/faces/claus_blood2.jpg
	
	{
		map textures/models/human/faces/claus_blood2.jpg
		rgbGen lightingSpherical
	}

}

claus_blood3
{
	qer_editorimage textures/models/human/faces/claus_blood3.jpg
	
	{
		map textures/models/human/faces/claus_blood3.jpg
		rgbGen lightingSpherical
	}

}

colonel_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/colonel/pants_colonel_blood1.jpg
	{
		map textures/models/human/germanmaps/colonel/pants_colonel_blood1.jpg
		rgbGen lightingSpherical
	}

}

colonel_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/colonel/pants_colonel_blood2.jpg
	{
		map textures/models/human/germanmaps/colonel/pants_colonel_blood2.jpg
		rgbGen lightingSpherical
	}

}

colonel_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/colonel/pants_colonel_blood3.jpg
	{
		map textures/models/human/germanmaps/colonel/pants_colonel_blood3.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood1.jpg
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood1.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood2.jpg
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood2.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood3.jpg
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood3.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood1.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood2.jpg
		rgbGen lightingSpherical
	}

}

colonel_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/colonel/tunic_colonel_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/colonel/tunic_colonel_blood3.jpg
		rgbGen lightingSpherical
	}

}

crusher_ss_feldgrau_blood1
{
	qer_editorimage textures/models/human/ssgear/ncohat_ss_feldgrau_blood1.jpg
	cull none
	{
		map textures/models/human/ssgear/ncohat_ss_feldgrau_blood1.jpg
		rgbGen lightingSpherical
	}

}

crusher_ss_feldgrau_blood2
{
	qer_editorimage textures/models/human/ssgear/ncohat_ss_feldgrau_blood2.jpg
	cull none
	{
		map textures/models/human/ssgear/ncohat_ss_feldgrau_blood2.jpg
		rgbGen lightingSpherical
	}

}

crusher_ss_feldgrau_blood3
{
	qer_editorimage textures/models/human/ssgear/ncohat_ss_feldgrau_blood3.jpg
	cull none
	{
		map textures/models/human/ssgear/ncohat_ss_feldgrau_blood3.jpg
		rgbGen lightingSpherical
	}

}

cull_motorpool_trench_blood1
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood1.jpg
		rgbGen lightingSpherical
	}

}

cull_motorpool_trench_blood2
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood2.jpg
		rgbGen lightingSpherical
	}

}

cull_motorpool_trench_blood3
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood3.jpg
		rgbGen lightingSpherical
	}

}

cull_pilot_pants_blood3
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood3.jpg
	cull none
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

cull_scientistcoat_blood1
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/scientist/scoat_blood1.jpg
		rgbGen lightingSpherical
	}

}

cull_scientistcoat_blood2
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/scientist/scoat_blood2.jpg
		rgbGen lightingSpherical
	}

}

cull_scientistcoat_blood3
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/scientist/scoat_blood3.jpg
		rgbGen lightingSpherical
	}

}

cull_winterpants1_art_blood1
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood1.jpg
		rgbGen lightingSpherical
	}

}

cull_winterpants1_art_blood2
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood2.jpg
		rgbGen lightingSpherical
	}

}

cull_winterpants1_art_blood3
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood3.jpg
		rgbGen lightingSpherical
	}

}

facewrap_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAkfacewrap.tga
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/models/human/germanmaps/afrikakorps/DAkfacewrap.tga
		rgbGen lightingSpherical
		blendfunc gl_one_minus_src_alpha gl_src_alpha 
	}

}

facewrap_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAkfacewrap.tga
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/models/human/germanmaps/afrikakorps/DAkfacewrap.tga
		rgbGen lightingSpherical
		blendfunc gl_one_minus_src_alpha gl_src_alpha 
	}

}

grenadier_shells_blood1
{
	qer_editorimage textures/models/human/germanmaps/german_grenadier/shells_blood1.jpg
	{
		map textures/models/human/germanmaps/german_grenadier/shells_blood1.jpg
		rgbGen lightingSpherical
		blendfunc blend
	}

}

grenadier_shells_blood2
{
	qer_editorimage textures/models/human/germanmaps/german_grenadier/shells_blood2.jpg
	{
		map textures/models/human/germanmaps/german_grenadier/shells_blood2.jpg
		rgbGen lightingSpherical
		blendfunc blend
	}

}

grenadier_shells_blood3
{
	qer_editorimage textures/models/human/germanmaps/german_grenadier/shells_blood3.jpg
	{
		map textures/models/human/germanmaps/german_grenadier/shells_blood3.jpg
		rgbGen lightingSpherical
		blendfunc blend
	}

}

hands_snow1_blood1
{
	qer_editorimage textures/models/human/hands_snow1_blood1.jpg
	{
		map textures/models/human/hands_snow1_blood1.jpg
		rgbGen lightingSpherical
	}

}

hands_snow1_blood2
{
	qer_editorimage textures/models/human/hands_snow1_blood2.jpg
	{
		map textures/models/human/hands_snow1_blood2.jpg
		rgbGen lightingSpherical
	}

}

hands_snow1_blood3
{
	qer_editorimage textures/models/human/hands_snow1_blood3.jpg
	{
		map textures/models/human/hands_snow1_blood3.jpg
		rgbGen lightingSpherical
	}

}

hands_snow2_blood1
{
	qer_editorimage textures/models/human/hands_snow2_blood1.jpg
	{
		map textures/models/human/hands_snow2_blood1.jpg
		rgbGen lightingSpherical
	}

}

hands_snow2_blood2
{
	qer_editorimage textures/models/human/hands_snow2_blood2.jpg
	{
		map textures/models/human/hands_snow2_blood2.jpg
		rgbGen lightingSpherical
	}

}

hands_snow2_blood3
{
	qer_editorimage textures/models/human/hands_snow2_blood3.jpg
	{
		map textures/models/human/hands_snow2_blood3.jpg
		rgbGen lightingSpherical
	}

}

handsnew_blood1
{
	qer_editorimage textures/models/human/handsnew_blood1.jpg
	{
		map textures/models/human/handsnew_blood1.jpg
		rgbGen lightingSpherical
	}

}

handsnew_blood2
{
	qer_editorimage textures/models/human/handsnew_blood2.jpg
	{
		map textures/models/human/handsnew_blood2.jpg
		rgbGen lightingSpherical
	}

}

handssnow_blood1
{
	qer_editorimage textures/models/human/handsglove_blood1.jpg
	{
		map textures/models/human/handsglove_blood1.jpg
		rgbGen lightingSpherical
	}

}

handssnow_blood2
{
	qer_editorimage textures/models/human/handsglove_blood2.jpg
	{
		map textures/models/human/handsglove_blood2.jpg
		rgbGen lightingSpherical
	}

}

handssnow_blood3
{
	qer_editorimage textures/models/human/handsglove_blood3.jpg
	{
		map textures/models/human/handsglove_blood3.jpg
		rgbGen lightingSpherical
	}

}

hbt_jacket_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood3.jpg
		rgbGen lightingSpherical
	}

}

hbt_jacket_c_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood3.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood3.jpg
		rgbGen lightingSpherical
	}

}

hbt_jacket_c_snow_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood3.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood3.jpg
		rgbGen lightingSpherical
	}

}

hbt_jacket_snow_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood3.jpg
		rgbGen lightingSpherical
	}

}

hbtpants_snow_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_snw_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_snw_blood3.jpg
		rgbGen lightingSpherical
	}

}

helmet_covered_ss2_blood1
{
	qer_editorimage textures/models/human/ssgear/camohelm_ss2_blood1.jpg		
	cull none
	{
		map textures/models/human/ssgear/camohelm_ss2_blood1.jpg
		rgbGen lightingSpherical
	}

}

helmet_covered_ss2_blood2
{
	qer_editorimage textures/models/human/ssgear/camohelm_ss2_blood2.jpg		
	cull none
	{
		map textures/models/human/ssgear/camohelm_ss2_blood2.jpg
		rgbGen lightingSpherical
	}

}

helmet_covered_ss2_blood3
{
	qer_editorimage textures/models/human/ssgear/camohelm_ss2_blood3.jpg		
	cull none
	{
		map textures/models/human/ssgear/camohelm_ss2_blood3.jpg
		rgbGen lightingSpherical
	}

}

hopper_blood1
{
	qer_editorimage textures/models/human/faces/hopper_blood1.jpg
	{
		map textures/models/human/faces/hopper_blood1.jpg
		rgbGen lightingSpherical
	}

}

hopper_blood2
{
	qer_editorimage textures/models/human/faces/hopper_blood2.jpg
	{
		map textures/models/human/faces/hopper_blood2.jpg
		rgbGen lightingSpherical
	}

}

jeff_blood1
{
	qer_editorimage textures/models/human/faces/jeff_blood1.jpg
	
	{
		map textures/models/human/faces/jeff_blood1.jpg
		rgbGen lightingSpherical
	}

}

jeff_blood2
{
	qer_editorimage textures/models/human/faces/jeff_blood2.jpg
	
	{
		map textures/models/human/faces/jeff_blood2.jpg
		rgbGen lightingSpherical
	}

}

jeff_blood3
{
	qer_editorimage textures/models/human/faces/jeff_blood3.jpg
	
	{
		map textures/models/human/faces/jeff_blood3.jpg
		rgbGen lightingSpherical
	}

}

jeff_c_blood1
{
	qer_editorimage textures/models/human/faces/jeff.tga
	
	{
		map textures/models/human/faces/jeff_c_blood1.jpg
		rgbGen lightingSpherical
	}

}

jeff_c_blood2
{
	qer_editorimage textures/models/human/faces/jeff.tga
	
	{
		map textures/models/human/faces/jeff_c_blood2.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_pants_blood1.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_pants_blood1.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_pants_blood2.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_pants_blood2.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_pants_blood3.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_shirt_blood1
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_shirt_blood1.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_shirt_blood1.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_shirt_blood2
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_shirt_blood2.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_shirt_blood2.jpg
		rgbGen lightingSpherical
	}

}

kmarrine_shirt_blood3
{
	qer_editorimage textures/models/human/germanmaps/kreigsmarine/km_shirt_blood3.jpg
	{
		map textures/models/human/germanmaps/kreigsmarine/km_shirt_blood3.jpg
		rgbGen lightingSpherical
	}

}

knitgloves1_blood1
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/knitgloves1_blood1.jpg
	{
		map textures/models/human/germanmaps/wintertroops/knitgloves1_blood1.jpg
		rgbGen lightingSpherical
	}

}

knitgloves1_blood2
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/knitgloves1_blood2.jpg
	{
		map textures/models/human/germanmaps/wintertroops/knitgloves1_blood2.jpg
		rgbGen lightingSpherical
	}

}

l_gloves_blood1
{
	qer_editorimage textures/models/human/germanmaps/tank_commander/l_gloves.tga
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/models/human/germanmaps/tank_commander/l_gloves.tga
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}

}

l_gloves_blood2
{
	qer_editorimage textures/models/human/germanmaps/tank_commander/l_gloves.tga
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/models/human/germanmaps/tank_commander/l_gloves.tga
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}

}

l_gloves_blood3
{
	qer_editorimage textures/models/human/germanmaps/tank_commander/l_gloves.tga
	{
		map textures/common/reflection1_blood3.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/models/human/germanmaps/tank_commander/l_gloves.tga
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}

}

manon_hands_blood1
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_hands_blood1.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_hands_blood1.jpg
		rgbGen lightingSpherical
	}

}

manon_hands_blood2
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_hands_blood2.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_hands_blood2.jpg
		rgbGen lightingSpherical
	}

}

manon_hands_blood3
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_hands_blood3.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_hands_blood3.jpg
		rgbGen lightingSpherical
	}

}

manon_head_blood1
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_head_blood1.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_head_blood1.jpg
		rgbGen lightingSpherical
	}

}

manon_head_blood2
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_head_blood2.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_head_blood2.jpg
		rgbGen lightingSpherical
	}

}

manon_head_blood3
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_head_blood3.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_head_blood3.jpg
		rgbGen lightingSpherical
	}

}

manon_pants_blood3
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_pants_blood3.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

manon_shirt_blood3
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood3.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood3.jpg
		rgbGen lightingSpherical
	}

}

motorpool_trench_blood1
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood1.jpg
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood1.jpg
		rgbGen lightingSpherical
	}

}

motorpool_trench_blood2
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood2.jpg
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood2.jpg
		rgbGen lightingSpherical
	}

}

motorpool_trench_blood3
{
	qer_editorimage textures/models/human/germanmaps/motorpool/trenchcoat_blood3.jpg
	{
		map textures/models/human/germanmaps/motorpool/trenchcoat_blood3.jpg
		rgbGen lightingSpherical
	}

}

old_dog_blood1
{
	qer_editorimage textures/models/human/faces/old_dog_blood1.jpg
	{
		map textures/models/human/faces/old_dog_blood1.jpg
		rgbGen lightingSpherical
	}

}

old_dog_blood2
{
	qer_editorimage textures/models/human/faces/old_dog_blood2.jpg
	{
		map textures/models/human/faces/old_dog_blood2.jpg
		rgbGen lightingSpherical
	}

}

paul_blood1
{
	qer_editorimage textures/models/human/faces/paul_blood1.jpg
	cull none	
	{
		map textures/models/human/faces/paul_blood1.jpg
		rgbGen lightingSpherical
	}

}

paul_blood2
{
	qer_editorimage textures/models/human/faces/paul_blood2.jpg
	cull none	
	{
		map textures/models/human/faces/paul_blood2.jpg
		rgbGen lightingSpherical
	}

}

paul_blood3
{
	qer_editorimage textures/models/human/faces/paul_blood3.jpg
	cull none	
	{
		map textures/models/human/faces/paul_blood3.jpg
		rgbGen lightingSpherical
	}

}

paul_dirty_blood1
{
	qer_editorimage textures/models/human/faces/paul_dirty_blood1.jpg
	
	{
		map textures/models/human/faces/paul_dirty_blood1.jpg
		rgbGen lightingSpherical
	}

}

paul_dirty_blood2
{
	qer_editorimage textures/models/human/faces/paul_dirty_blood2.jpg
	
	{
		map textures/models/human/faces/paul_dirty_blood2.jpg
		rgbGen lightingSpherical
	}

}

pilot_pants_blood3
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood3.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

pilot_top_blood3
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_top_blood3.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_top_blood3.jpg
		rgbGen lightingSpherical
	}

}

pt_hands_blood1
{
	qer_editorimage textures/models/human/pt_hands_blood1.jpg
	{
		map textures/models/human/pt_hands_blood1.jpg
		rgbGen lightingSpherical
	}

}

pt_hands_blood2
{
	qer_editorimage textures/models/human/pt_hands_blood2.jpg
	{
		map textures/models/human/pt_hands_blood2.jpg
		rgbGen lightingSpherical
	}

}

radiopack_blood1
{
	qer_editorimage textures/models/equipment/radiopack_blood1.jpg
	{
		map textures/models/equipment/radiopack_blood1.jpg
		rgbGen lightingSpherical
	}

}

radiopack_blood2
{
	qer_editorimage textures/models/equipment/radiopack_blood2.jpg
	{
		map textures/models/equipment/radiopack_blood2.jpg
		rgbGen lightingSpherical
	}

}

radiopack_blood3
{
	qer_editorimage textures/models/equipment/radiopack_blood3.jpg
	{
		map textures/models/equipment/radiopack_blood3.jpg
		rgbGen lightingSpherical
	}

}

ranger_pants_snw_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood3.jpg
		rgbGen lightingSpherical
	}

}

ranger_top_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_blood1.jpg
		rgbGen lightingSpherical
	}

}

ranger_top_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_blood2.jpg
		rgbGen lightingSpherical
	}

}

ranger_top_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_blood3.jpg
		rgbGen lightingSpherical
	}

}

ranger_top_snw_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_brit_cmd_tunic_blood3
{
	qer_editorimage textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood3.jpg
	{
		map textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_brit_inf_pants_blood3
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood3.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_brit_inf_tunic_blood3
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood3.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_mcmartin_blood1
{
	qer_editorimage textures/models/human/faces/Sc_Al_Mcmartin_blood1.jpg
	
	{
		map textures/models/human/faces/Sc_Al_Mcmartin_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_al_mcmartin_blood2
{
	qer_editorimage textures/models/human/faces/Sc_Al_Mcmartin_blood2.jpg
	
	{
		map textures/models/human/faces/Sc_Al_Mcmartin_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_al_mcmartin_blood3
{
	qer_editorimage textures/models/human/faces/Sc_Al_Mcmartin_blood3.jpg
	
	{
		map textures/models/human/faces/Sc_Al_Mcmartin_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_gen_tunic_blood1
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood1.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_gen_tunic_blood2
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood2.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_gen_tunic_blood3
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood3.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_gen_Tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_med_tunic_blood1
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood1.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_med_tunic_blood2
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood2.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_med_tunic_blood3
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood3.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Med_Tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_tank_tunic_blood1
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood1.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_tank_tunic_blood2
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood2.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_al_us_tank_tunic_blood3
{
	qer_editorimage textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood3.jpg
	{
		map textures/models/human/usmaintt/SC_AL_US_Tank_Tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_pant_blood1
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood1.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_pant_blood2
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood2.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_pant_blood3
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood3.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Pant_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_tunic_blood1
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood1.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_tunic_blood2
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood2.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf2_tunic_blood3
{
	qer_editorimage textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood3.jpg
	{
		map textures/models/human/ItalMaintt/Sc_AX_Ital_Inf2_Tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_pants_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_pant.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_pant_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_pants_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_pant.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_pant_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_pants_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_pant.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_pant_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_tunic_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_tunic.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_tunic_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_tunic.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_inf_tunic_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/Sc_AX_Ital_Inf_tunic.tga
	{
		map textures/models/human/italmaintt/Sc_AX_Ital_Inf_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_pant_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_Pant.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_Pant_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_pant_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_Pant.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_Pant_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_pant_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_Pant.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_Pant_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_tunic_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_tunic.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_tunic_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_tunic.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_para_tunic_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/SC_AX_Ital_Para_tunic.tga
	{
		map textures/models/human/ItalMaintt/SC_AX_Ital_Para_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_pant_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_Pant.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_Pant_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_pant_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_Pant.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_Pant_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_pant_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_Pant.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_Pant_blood3.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_tunic_blood1
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_tunic.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_tunic_blood2
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_tunic.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

sc_ax_ital_vol_tunic_blood3
{
	qer_editorimage textures/models/Human/ItalMaintt/It_AX_Ital_Vol_tunic.tga
	{
		map textures/models/human/ItalMaintt/It_AX_Ital_Vol_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

scientistcoat_blood1
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood1.jpg
	{
		map textures/models/human/germanmaps/scientist/scoat_blood1.jpg
		rgbGen lightingSpherical
	}

}

scientistcoat_blood2
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood2.jpg
	{
		map textures/models/human/germanmaps/scientist/scoat_blood2.jpg
		rgbGen lightingSpherical
	}

}

scientistcoat_blood3
{
	qer_editorimage textures/models/human/germanmaps/scientist/scoat_blood3.jpg
	{
		map textures/models/human/germanmaps/scientist/scoat_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_corporal_pants_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_pants_blood3.jpg
	{
		map textures/models/human/sovietmaps/soviet_corporal_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_corporal_tunic_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_tunic_blood3.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_corporal_tunic_blood3.jpg
		rgbGen lightingSpherical

	}

}

soviet_infantry_pants_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_pants_blood3.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_infantry_tunic_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood3.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_infantry_tunic_c_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood3.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_pants_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_pants_blood1.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_pants_blood1.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_pants_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_pants_blood2.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_pants_blood2.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_pants_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_pants_blood3.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_tunic_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_tunic_blood1.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_tunic_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_tunic_blood2.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

soviet_officer_tunic_blood3
{
	qer_editorimage textures/models/human/sovietmaps/soviet_officer_tunic_blood3.jpg
	{
		map textures/models/human/sovietmaps/soviet_officer_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_1_blood1
{
	qer_editorimage textures/models/human/faces/soviet_pvt_1_blood1.jpg
	{
		map textures/models/human/faces/soviet_pvt_1_blood1.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_1_blood2
{
	qer_editorimage textures/models/human/faces/soviet_pvt_1_blood2.jpg
	{
		map textures/models/human/faces/soviet_pvt_1_blood2.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_1_blood3
{
	qer_editorimage textures/models/human/faces/soviet_pvt_1_blood3.jpg
	{
		map textures/models/human/faces/soviet_pvt_1_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_2_blood1
{
	qer_editorimage textures/models/human/faces/soviet_pvt_2_blood1.jpg
	{
		map textures/models/human/faces/soviet_pvt_2_blood1.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_2_blood2
{
	qer_editorimage textures/models/human/faces/soviet_pvt_2_blood2.jpg
	{
		map textures/models/human/faces/soviet_pvt_2_blood2.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_2_blood3
{
	qer_editorimage textures/models/human/faces/soviet_pvt_2_blood3.jpg
	{
		map textures/models/human/faces/soviet_pvt_2_blood3.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_3_blood1
{
	qer_editorimage textures/models/human/faces/soviet_pvt_3_blood1.jpg
	{
		map textures/models/human/faces/soviet_pvt_3_blood1.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_3_blood2
{
	qer_editorimage textures/models/human/faces/soviet_pvt_3_blood2.jpg
	{
		map textures/models/human/faces/soviet_pvt_3_blood2.jpg
		rgbGen lightingSpherical
	}

}

soviet_pvt_3_blood3
{
	qer_editorimage textures/models/human/faces/soviet_pvt_3_blood3.jpg
	{
		map textures/models/human/faces/soviet_pvt_3_blood3.jpg
		rgbGen lightingSpherical
	}

}

srg_dirty_blood1
{
	qer_editorimage textures/models/human/faces/srg_dirty_blood1.jpg
	cull none	
	{
		map textures/models/human/faces/srg_dirty_blood1.jpg
		rgbGen lightingSpherical
	}

}

srg_dirty_blood2
{
	qer_editorimage textures/models/human/faces/srg_dirty_blood2.jpg
	cull none	
	{
		map textures/models/human/faces/srg_dirty_blood2.jpg
		rgbGen lightingSpherical
	}

}

srg_dirty_blood3
{
	qer_editorimage textures/models/human/faces/srg_dirty_blood3.jpg
	cull none	
	{
		map textures/models/human/faces/srg_dirty_blood3.jpg
		rgbGen lightingSpherical
	}

}

tom_blood1
{
	qer_editorimage textures/models/human/faces/tom_blood1.jpg
	
	{
		map textures/models/human/faces/tom_blood1.jpg
		rgbGen lightingSpherical
	}

}

tom_blood2
{
	qer_editorimage textures/models/human/faces/tom_blood2.jpg
	
	{
		map textures/models/human/faces/tom_blood2.jpg
		rgbGen lightingSpherical
	}

}

uk_head_pt_1_blood1
{
	qer_editorimage textures/models/human/faces/uk_pt_1_blood1.jpg
	{
		map textures/models/human/faces/uk_pt_1_blood1.jpg
		rgbGen static
	}

}

uk_head_pt_1_blood2
{
	qer_editorimage textures/models/human/faces/uk_pt_1_blood2.jpg
	{
		map textures/models/human/faces/uk_pt_1_blood2.jpg
		rgbGen static
	}

}

uk_head_pt_1_blood3
{
	qer_editorimage textures/models/human/faces/uk_pt_1_blood3.jpg
	{
		map textures/models/human/faces/uk_pt_1_blood3.jpg
		rgbGen static
	}

}

uk_head_pt_2_blood1
{
	qer_editorimage textures/models/human/faces/uk_pt_2_blood1.jpg
	{
		map textures/models/human/faces/uk_pt_2_blood1.jpg
		rgbGen lightingSpherical
	}

}

uk_head_pt_2_blood2
{
	qer_editorimage textures/models/human/faces/uk_pt_2_blood2.jpg
	{
		map textures/models/human/faces/uk_pt_2_blood2.jpg
		rgbGen lightingSpherical
	}

}

uk_head_pt_3_blood1
{
	qer_editorimage textures/models/human/faces/uk_pt_3_blood1.jpg
	{
		map textures/models/human/faces/uk_pt_3_blood1.jpg
		rgbGen static
	}

}

uk_head_pt_3_blood2
{
	qer_editorimage textures/models/human/faces/uk_pt_3_blood2.jpg
	{
		map textures/models/human/faces/uk_pt_3_blood2.jpg
		rgbGen static
	}

}

uk_head_pt_3_blood3
{
	qer_editorimage textures/models/human/faces/uk_pt_3_blood3.jpg
	{
		map textures/models/human/faces/uk_pt_3_blood3.jpg
		rgbGen static
	}

}

uk_head_pt_capt_blood1
{
	qer_editorimage textures/models/human/faces/uk_pt_capt_blood1.jpg
	{
		map textures/models/human/faces/uk_pt_capt_blood1.jpg
		rgbGen lightingSpherical
	}

}

uk_head_pt_capt_blood2
{
	qer_editorimage textures/models/human/faces/uk_pt_capt_blood2.jpg
	{
		map textures/models/human/faces/uk_pt_capt_blood2.jpg
		rgbGen lightingSpherical
	}

}

uk_head_pt_capt_blood3
{
	qer_editorimage textures/models/human/faces/uk_pt_capt_blood3.jpg
	{
		map textures/models/human/faces/uk_pt_capt_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_bob_blood1
{
	qer_editorimage textures/models/human/faces/us_bob_blood1.jpg
	
	{
		map textures/models/human/faces/us_bob_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_bob_blood2
{
	qer_editorimage textures/models/human/faces/us_bob_blood2.jpg
	
	{
		map textures/models/human/faces/us_bob_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_chance_blood1
{
	qer_editorimage textures/models/human/faces/us_chance_blood1.jpg
	
	{
		map textures/models/human/faces/us_chance_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_chance_blood2
{
	qer_editorimage textures/models/human/faces/us_chance_blood2.jpg
	
	{
		map textures/models/human/faces/us_chance_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_1_blood1
{
	qer_editorimage textures/models/human/faces/us_pt_1_blood1.jpg
	
	{
		map textures/models/human/faces/us_pt_1_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_1_blood2
{
	qer_editorimage textures/models/human/faces/us_pt_1_blood2.jpg
	
	{
		map textures/models/human/faces/us_pt_1_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_1_blood3
{
	qer_editorimage textures/models/human/faces/us_pt_1_blood3.jpg
	
	{
		map textures/models/human/faces/us_pt_1_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_2_blood1
{
	qer_editorimage textures/models/human/faces/us_pt_2_blood1.jpg
	
	{
		map textures/models/human/faces/us_pt_2_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_2_blood2
{
	qer_editorimage textures/models/human/faces/us_pt_2_blood2.jpg
	
	{
		map textures/models/human/faces/us_pt_2_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_2_blood3
{
	qer_editorimage textures/models/human/faces/us_pt_2_blood3.jpg
	
	{
		map textures/models/human/faces/us_pt_2_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_head_pt_3_blood1
{
	qer_editorimage textures/models/human/faces/us_pt_3_blood1.jpg
	{
		map textures/models/human/faces/us_pt_3_blood1.jpg
		rgbGen static
	}

}

us_head_pt_3_blood2
{
	qer_editorimage textures/models/human/faces/us_pt_3_blood2.jpg
	{
		map textures/models/human/faces/us_pt_3_blood2.jpg
		rgbGen static
	}

}

us_head_pt_3_blood3
{
	qer_editorimage textures/models/human/faces/us_pt_3_blood3.jpg
	{
		map textures/models/human/faces/us_pt_3_blood3.jpg
		rgbGen static
	}

}

us_head_snow_1_blood1
{
	qer_editorimage textures/models/human/faces/us_snow_1_blood1.jpg
	
	{
		map textures/models/human/faces/us_snow_1_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_1_blood2
{
	qer_editorimage textures/models/human/faces/us_snow_1_blood2.jpg
	
	{
		map textures/models/human/faces/us_snow_1_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_1_blood3
{
	qer_editorimage textures/models/human/faces/us_snow_1_blood3.jpg
	
	{
		map textures/models/human/faces/us_snow_1_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_2_blood1
{
	qer_editorimage textures/models/human/faces/us_snow_2_blood1.jpg
	
	{
		map textures/models/human/faces/us_snow_2_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_2_blood2
{
	qer_editorimage textures/models/human/faces/us_snow_2_blood2.jpg
	
	{
		map textures/models/human/faces/us_snow_2_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_2_blood3
{
	qer_editorimage textures/models/human/faces/us_snow_2_blood3.jpg
	
	{
		map textures/models/human/faces/us_snow_2_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_head_snow_3_blood1
{
	qer_editorimage textures/models/human/faces/us_snow_3_blood1.jpg
	{
		map textures/models/human/faces/us_snow_3_blood1.jpg
		rgbGen static
	}

}

us_head_snow_3_blood2
{
	qer_editorimage textures/models/human/faces/us_snow_3_blood2.jpg
	{
		map textures/models/human/faces/us_snow_3_blood2.jpg
		rgbGen static
	}

}

us_head_snow_3_blood3
{
	qer_editorimage textures/models/human/faces/us_snow_3_blood3.jpg
	{
		map textures/models/human/faces/us_snow_3_blood3.jpg
		rgbGen static
	}

}

us_head_snow_capt_blood1
{
	qer_editorimage textures/models/human/faces/us_snow_captain_blood1.jpg
	{
		map textures/models/human/faces/us_snow_captain_blood1.jpg
		rgbGen static
	}

}

us_head_snow_capt_blood2
{
	qer_editorimage textures/models/human/faces/us_snow_captain_blood2.jpg
	{
		map textures/models/human/faces/us_snow_captain_blood2.jpg
		rgbGen static
	}

}

us_head_snow_capt_blood3
{
	qer_editorimage textures/models/human/faces/us_snow_captain_blood3.jpg
	{
		map textures/models/human/faces/us_snow_captain_blood3.jpg
		rgbGen static
	}

}

us_head_snow_medic_blood1
{
	qer_editorimage textures/models/human/faces/us_snow_medic_blood1.jpg
	{
		map textures/models/human/faces/us_snow_medic_blood1.jpg
		rgbGen static
	}

}

us_head_snow_medic_blood2
{
	qer_editorimage textures/models/human/faces/us_snow_medic_blood2.jpg
	{
		map textures/models/human/faces/us_snow_medic_blood2.jpg
		rgbGen static
	}

}

us_head_snow_medic_blood3
{
	qer_editorimage textures/models/human/faces/us_snow_medic_blood3.jpg
	{
		map textures/models/human/faces/us_snow_medic_blood3.jpg
		rgbGen static
	}

}

us_j_blood1
{
	qer_editorimage textures/models/human/faces/us_j_blood1.jpg
	
	{
		map textures/models/human/faces/us_j_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_j_blood2
{
	qer_editorimage textures/models/human/faces/us_j_blood2.jpg
	
	{
		map textures/models/human/faces/us_j_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_north_blood1
{
	qer_editorimage textures/models/human/faces/us_north_blood1.jpg
	
	{
		map textures/models/human/faces/us_north_blood1.jpg
		rgbGen lightingSpherical
	}

}

us_north_blood2
{
	qer_editorimage textures/models/human/faces/us_north_blood2.jpg
	
	{
		map textures/models/human/faces/us_north_blood2.jpg
		rgbGen lightingSpherical
	}

}

us_top_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood3.jpg
		rgbGen lightingSpherical
	}

}

us_top_c_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood3.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood3.jpg
		rgbGen lightingSpherical
	}

}

usa_pt_pants_blood3
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_pants_blood3.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_pants_blood3.jpg
		rgbGen lightingSpherical
	}

}

usa_pt_top_blood3
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood3.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood3.jpg
		rgbGen lightingSpherical
	}

}

usa_pt_top_cull_blood3
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood3.jpg
	cull none
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood3.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood1.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood1.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood2.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood2.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood3.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_tunic_blood3.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_blood1
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood1.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood1.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_blood2
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood2.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood2.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_blood3
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood3.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood3.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood1.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood2.jpg
		rgbGen lightingSpherical
	}

}

wehrmact_tunic_fieldgrey_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/wehrmact/Wtunicfgrey_blood3.jpg
		rgbGen lightingSpherical
	}

}

wheathers_blood1
{
	qer_editorimage textures/models/human/faces/wheathers_blood1.jpg
	
	{
		map textures/models/human/faces/wheathers_blood1.jpg
		rgbGen lightingSpherical
	}

}

wheathers_blood2
{
	qer_editorimage textures/models/human/faces/wheathers_blood2.jpg
	
	{
		map textures/models/human/faces/wheathers_blood2.jpg
		rgbGen lightingSpherical
	}

}

wheathers_blood3
{
	qer_editorimage textures/models/human/faces/wheathers_blood3.jpg
	
	{
		map textures/models/human/faces/wheathers_blood3.jpg
		rgbGen lightingSpherical
	}

}

winterpants1_art_blood1
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood1.jpg
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood1.jpg
		rgbGen lightingSpherical
	}

}

winterpants1_art_blood2
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood2.jpg
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood2.jpg
		rgbGen lightingSpherical
	}

}

winterpants1_art_blood3
{
	qer_editorimage textures/models/human/germanmaps/w/winterpants1_art_blood3.jpg
	{
		map textures/models/human/germanmaps/w/winterpants1_art_blood3.jpg
		rgbGen lightingSpherical
	}

}

wintertop1_art_blood1
{
	qer_editorimage textures/models/human/germanmaps/w/wintertop1_art_blood1.jpg
	{
		map textures/models/human/germanmaps/w/wintertop1_art_blood1.jpg
		rgbGen lightingSpherical
	}

}

wintertop1_art_blood2
{
	qer_editorimage textures/models/human/germanmaps/w/wintertop1_art_blood2.jpg
	{
		map textures/models/human/germanmaps/w/wintertop1_art_blood2.jpg
		rgbGen lightingSpherical
	}

}

wintertop1_art_blood3
{
	qer_editorimage textures/models/human/germanmaps/w/wintertop1_art_blood3.jpg
	{
		map textures/models/human/germanmaps/w/wintertop1_art_blood3.jpg
		rgbGen lightingSpherical
	}

}

wolfgang_blood1
{
	qer_editorimage textures/models/human/faces/wolfgang_blood1.jpg
	
	{
		map textures/models/human/faces/wolfgang_blood1.jpg
		rgbGen lightingSpherical
	}

}

wolfgang_blood2
{
	qer_editorimage textures/models/human/faces/wolfgang_blood2.jpg
	
	{
		map textures/models/human/faces/wolfgang_blood2.jpg
		rgbGen lightingSpherical
	}

}
