// HZM coop - GORE TIER 1 (damage-tier blood skins). GENERATED by
// scratchpad/gen_gore_skins.py - do not hand-edit, re-run the generator.
// Every _blood1/_blood2 shader is a clone of the model's original surface
// shader retargeted at a composited diffuse whose blood pixels are exactly
// RGB(21,2,0) #150200 fresh / (7,1,0) dried (mod blood color authority -
// see _research/player_gore_research.md 6c). The german_wehrmact_soldier
// heavy variant is alpha-tested (alphaFunc GE128 + cull none): its texture
// carries punched-out bullet holes in the alpha channel (prototype).

ranger_pants_snw_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood1.jpg
		rgbGen lightingSpherical
	}
}

ranger_pants_snw_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_snw_blood2.jpg
		rgbGen lightingSpherical
	}
}

ranger_top_snw_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood1.jpg
		rgbGen lightingSpherical
	}
}

ranger_top_snw_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_assaultvest_snw_blood2.jpg
		rgbGen lightingSpherical
	}
}

HBTpants_snow_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_snw_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_snw_blood1.jpg
		rgbGen lightingSpherical
	}
}

HBTpants_snow_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_snw_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_snw_blood2.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_snow_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood1.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_snow_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood2.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_c_snow_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood1.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood1.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_c_snow_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_snw_blood2.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_snw_blood2.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_top_blood1
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood1.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_top_blood2
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood2.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_pants_blood1
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_pants_blood1.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_pants_blood2
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_pants_blood2.jpg
	{
		map textures/models/human/usa_paratrooper/air_pt_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_top_cull_blood1
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood1.jpg
	cull none
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

usa_pt_top_cull_blood2
{
	qer_editorimage textures/models/human/usa_paratrooper/air_pt_coat_blood2.jpg
	cull none
	{
		map textures/models/human/usa_paratrooper/air_pt_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_1_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_1_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_1_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_1_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_1_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_1_blood2.jpg
		rgbGen lightingSpherical
	}
}

airborne_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/air_pants_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/air_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

airborne_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/air_pants_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/air_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_2_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_2_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_2_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_2_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_2_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_2_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_cpl_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_cpl_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_cpl_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_cpl_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_cpl_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_cpl_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_ssgt_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_ssgt_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_ssgt_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_101st_ssgt_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_101st_ssgt_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_101st_ssgt_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_1_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_1_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_1_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_1_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_1_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_1_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_t5_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_t5_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_t5_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_t5_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_t5_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_t5_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_cpl_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_cpl_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_cpl_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_cpl_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_cpl_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_cpl_blood2.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_ssgt_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_ssgt_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_ssgt_blood1.jpg
		rgbGen lightingSpherical
	}
}

air_jacket_82nd_ssgt_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/aircoat_82nd_ssgt_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/aircoat_82nd_ssgt_blood2.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_blood1
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood1.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_blood2
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood2.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_pants_blood1
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_pants_blood1.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_pants_blood2
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_pants_blood2.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_cull_blood1
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood1.jpg
	cull none
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_cull_blood2
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood2.jpg
	cull none
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_brit_inf_Pants_blood1
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood1.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_brit_inf_Pants_blood2
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood2.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_Brit_CMD_Tunic_blood1
{
	qer_editorimage textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood1.jpg
	{
		map textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_Brit_CMD_Tunic_blood2
{
	qer_editorimage textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood2.jpg
	{
		map textures/models/human/britmaintt/Sc_AL_Brit_CMD_Tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

SC_AL_brit_inf_tunic_blood1
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood1.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

SC_AL_brit_inf_tunic_blood2
{
	qer_editorimage textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood2.jpg
	{
		map textures/models/human/britmaintt/SC_AL_brit_inf_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

manon_shirt_blood1
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood1.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood1.jpg
		rgbGen lightingSpherical
	}
}

manon_shirt_blood2
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood2.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood2.jpg
		rgbGen lightingSpherical
	}
}

c_manon_shirt_blood1
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood1.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood1.jpg
		rgbGen lightingSpherical
	}
}

c_manon_shirt_blood2
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_shirt_blood2.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_shirt_blood2.jpg
		rgbGen lightingSpherical
	}
}

manon_pants_blood1
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_pants_blood1.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

manon_pants_blood2
{
	qer_editorimage textures/models/human/frenchmaps/manon/manon_pants_blood2.jpg
	{
		map textures/models/human/frenchmaps/manon/manon_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

greypants_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/greypants_blood1.jpg
	{
		map textures/models/human/frenchmaps/resistance/greypants_blood1.jpg
		rgbGen lightingSpherical
	}
}

greypants_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/greypants_blood2.jpg
	{
		map textures/models/human/frenchmaps/resistance/greypants_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_greypants_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/greypants_blood1.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/greypants_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_greypants_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/greypants_blood2.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/greypants_blood2.jpg
		rgbGen lightingSpherical
	}
}

browncoat_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood1.jpg
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood1.jpg
		rgbGen lightingSpherical
	}
}

browncoat_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood2.jpg
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_browncoat_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood1.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_browncoat_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood2.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood2.jpg
		rgbGen lightingSpherical
	}
}

pilot_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood1.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

pilot_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood2.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

pilot_top_blood1
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_top_blood1.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_top_blood1.jpg
		rgbGen lightingSpherical
	}
}

pilot_top_blood2
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_top_blood2.jpg
	{
		map textures/models/human/usmaps/pilot/pilot_top_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_pilot_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood1.jpg
	cull none
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_pilot_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/pilot/pilot_pants_blood2.jpg
	cull none
	{
		map textures/models/human/usmaps/pilot/pilot_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

soviet_corporal_tunic_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_tunic_blood1.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_corporal_tunic_blood1.jpg
		rgbGen lightingSpherical

	}
}

soviet_corporal_tunic_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_tunic_blood2.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_corporal_tunic_blood2.jpg
		rgbGen lightingSpherical

	}
}

soviet_corporal_pants_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_pants_blood1.jpg
	{
		map textures/models/human/sovietmaps/soviet_corporal_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

soviet_corporal_pants_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_corporal_pants_blood2.jpg
	{
		map textures/models/human/sovietmaps/soviet_corporal_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_tunic_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood1.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_tunic_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood2.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_pants_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_pants_blood1.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_pants_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_pants_blood2.jpg
	{
		map textures/models/human/sovietmaps/soviet_infantry_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_tunic_c_blood1
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood1.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

soviet_infantry_tunic_c_blood2
{
	qer_editorimage textures/models/human/sovietmaps/soviet_infantry_tunic_blood2.jpg
	cull none
	{
		map textures/models/human/sovietmaps/soviet_infantry_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

brownpants_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood1.jpg
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood1.jpg
		rgbGen lightingSpherical
	}
}

brownpants_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood2.jpg
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_brownpants_blood1
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood1.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_brownpants_blood2
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood2.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood2.jpg
		rgbGen lightingSpherical
	}
}

tanker_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/tanker/tanker_pants_blood1.jpg
	{
		map textures/models/human/usmaps/tanker/tanker_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

tanker_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/tanker/tanker_pants_blood2.jpg
	{
		map textures/models/human/usmaps/tanker/tanker_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

tanker_top_blood1
{
	qer_editorimage textures/models/human/usmaps/tanker/tanker_top_blood1.jpg
	{
		map textures/models/human/usmaps/tanker/tanker_top_blood1.jpg
		rgbGen lightingSpherical
	}
}

tanker_top_blood2
{
	qer_editorimage textures/models/human/usmaps/tanker/tanker_top_blood2.jpg
	{
		map textures/models/human/usmaps/tanker/tanker_top_blood2.jpg
		rgbGen lightingSpherical
	}
}

allied_tech_tunic_blood1
{
	qer_editorimage textures/models/human/usmaps/tech/tunic_tech_blood1.jpg
	{
		map textures/models/human/usmaps/tech/tunic_tech_blood1.jpg
		rgbGen lightingSpherical
	}
}

allied_tech_tunic_blood2
{
	qer_editorimage textures/models/human/usmaps/tech/tunic_tech_blood2.jpg
	{
		map textures/models/human/usmaps/tech/tunic_tech_blood2.jpg
		rgbGen lightingSpherical
	}
}

allied_tech_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/tech/tech_pants_blood1.jpg
	{
		map textures/models/human/usmaps/tech/tech_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

allied_tech_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/tech/tech_pants_blood2.jpg
	{
		map textures/models/human/usmaps/tech/tech_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

ranger_pants_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_blood1.jpg
		rgbGen lightingSpherical
	}
}

ranger_pants_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_blood2.jpg
		rgbGen lightingSpherical
	}
}

us_top_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood1.jpg
		rgbGen lightingSpherical
	}
}

us_top_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood2.jpg
		rgbGen lightingSpherical
	}
}

us_top_c_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood1.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood1.jpg
		rgbGen lightingSpherical
	}
}

us_top_c_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket_blood2.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/ranger_jacket_blood2.jpg
		rgbGen lightingSpherical
	}
}

army_pantsgreen_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/army_pantsgreen_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/army_pantsgreen_blood1.jpg
		rgbGen lightingSpherical
	}
}

army_pantsgreen_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/army_pantsgreen_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/army_pantsgreen_blood2.jpg
		rgbGen lightingSpherical
	}
}

army_jacket_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/army_jacket_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/army_jacket_blood1.jpg
		rgbGen lightingSpherical
	}
}

army_jacket_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/army_jacket_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/army_jacket_blood2.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood1.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood2.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_c_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood1.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood1.jpg
		rgbGen lightingSpherical
	}
}

hbt_jacket_c_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/hbt_jacket_blood2.jpg
	cull none
	{
		map textures/models/human/usmaps/ranger/hbt_jacket_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_fgrey_blood1
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood1.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_fgrey_blood2
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood2.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_soldat_blood1
{
	qer_editorimage textures/models/human/heer/wh_soldat_blood1.jpg
	{
		map textures/models/human/heer/wh_soldat_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_soldat_blood2
{
	cull none
	qer_editorimage textures/models/human/heer/wh_soldat_blood2holes.tga
	{
		map textures/models/human/heer/wh_soldat_blood2holes.tga
		alphaFunc GE128
		depthWrite
		rgbGen lightingSpherical
	}
}

heer_pants_late_blood1
{
	qer_editorimage textures/models/human/heer/WPantsfgrey_alt_blood1.jpg				
	{
		map textures/models/human/heer/WPantsfgrey_alt_blood1.jpg
		rgbGen lightingSpherical
	}
}

heer_pants_late_blood2
{
	qer_editorimage textures/models/human/heer/WPantsfgrey_alt_blood2.jpg				
	{
		map textures/models/human/heer/WPantsfgrey_alt_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_pants_camo2_blood1
{
	qer_editorimage textures/models/human/heer/wh_pants_camo2_blood1.jpg
	{
		map textures/models/human/heer/wh_pants_camo2_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_pants_camo2_blood2
{
	qer_editorimage textures/models/human/heer/wh_pants_camo2_blood2.jpg
	{
		map textures/models/human/heer/wh_pants_camo2_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_sniper_blood1
{
	qer_editorimage textures/models/human/heer/wh_sniper_vet_blood1.jpg
	{
		map textures/models/human/heer/wh_sniper_vet_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_sniper_blood2
{
	qer_editorimage textures/models/human/heer/wh_sniper_vet_blood2.jpg
	{
		map textures/models/human/heer/wh_sniper_vet_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_alt_soldat_blood1
{
	qer_editorimage textures/models/human/heer/wh_alt_soldat_blood1.jpg		
	{
		map textures/models/human/heer/wh_alt_soldat_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_alt_soldat_blood2
{
	cull none
	qer_editorimage textures/models/human/heer/wh_alt_soldat_blood2holes.tga		
	{
		map textures/models/human/heer/wh_alt_soldat_blood2holes.tga
		alphaFunc GE128
		depthWrite
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_blood1
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_blood1.jpg
	{
		map textures/models/human/heer/wh_gefreiter_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_blood2
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_blood2.jpg
	{
		map textures/models/human/heer/wh_gefreiter_blood2.jpg
		rgbGen lightingSpherical
	}
}

handsnew_skin2
{
	qer_editorimage textures/models/human/handsnew_skin2.jpg
	{
		map textures/models/human/handsnew_skin2.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood1.jpg
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood2.jpg
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood2.jpg
		rgbGen lightingSpherical
	}
}

officer_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer/pants_officer_blood1.jpg
	{
		map textures/models/human/germanmaps/officer/pants_officer_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer/pants_officer_blood2.jpg
	{
		map textures/models/human/germanmaps/officer/pants_officer_blood2.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_vet_blood1
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_vet_blood1.jpg
	{
		map textures/models/human/heer/wh_gefreiter_vet_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_vet_blood2
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_vet_blood2.jpg
	{
		map textures/models/human/heer/wh_gefreiter_vet_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood1.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood2.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet_blood1
{
	qer_editorimage textures/models/human/heer/wh_nco_vet_blood1.jpg
	{
		map textures/models/human/heer/wh_nco_vet_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet_blood2
{
	qer_editorimage textures/models/human/heer/wh_nco_vet_blood2.jpg
	{
		map textures/models/human/heer/wh_nco_vet_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet2_blood1
{
	qer_editorimage textures/models/human/heer/wh_nco_vet2_blood1.jpg
	{
		map textures/models/human/heer/wh_nco_vet2_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet2_blood2
{
	qer_editorimage textures/models/human/heer/wh_nco_vet2_blood2.jpg
	{
		map textures/models/human/heer/wh_nco_vet2_blood2.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_blood1
{
	qer_editorimage textures/models/human/heer/wh_nco_blood1.jpg
	{
		map textures/models/human/heer/wh_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_blood2
{
	qer_editorimage textures/models/human/heer/wh_nco_blood2.jpg
	{
		map textures/models/human/heer/wh_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

wintertop1_blood1
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/wintertop1_blood1.jpg
	{
		map textures/models/human/germanmaps/wintertroops/wintertop1_blood1.jpg
		rgbGen lightingSpherical
	}
}

wintertop1_blood2
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/wintertop1_blood2.jpg
	{
		map textures/models/human/germanmaps/wintertroops/wintertop1_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_winterpants1_blood1
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_winterpants1_blood2
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood2.jpg
		rgbGen lightingSpherical
	}
}

winterpants1_blood1
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood1.jpg
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood1.jpg
		rgbGen lightingSpherical
	}
}

winterpants1_blood2
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood2.jpg
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood2.jpg
		rgbGen lightingSpherical
	}
}

knitgloves1_skin2
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/knitgloves1_skin2.jpg
	{
		map textures/models/human/germanmaps/wintertroops/knitgloves1_skin2.jpg
		rgbGen lightingSpherical
	}
}

mantel_blood1
{
	qer_editorimage textures/models/human/ger_winter/trenchcoat_blood1.jpg
	{
		map textures/models/human/ger_winter/trenchcoat_blood1.jpg
		rgbGen lightingSpherical
	}
}

mantel_blood2
{
	qer_editorimage textures/models/human/ger_winter/trenchcoat_blood2.jpg
	{
		map textures/models/human/ger_winter/trenchcoat_blood2.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzpants_blood1.jpg
	{
		map textures/models/human/germanmaps/shutzen/shutzpants_blood1.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzpants_blood2.jpg
	{
		map textures/models/human/germanmaps/shutzen/shutzpants_blood2.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood1.jpg
	
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood1.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood2.jpg
	
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood2.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_cull_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood1.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_cull_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood2.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_nco_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood1.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_nco_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood2.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_nco_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood1.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_nco_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood2.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

cull_shutzshirt_nco_blood1
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

cull_shutzshirt_nco_blood2
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood1.jpg
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood2.jpg
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood2.jpg
		rgbGen lightingSpherical
	}
}

officer2_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer2/pants_officer2_blood1.jpg
	{
		map textures/models/human/germanmaps/officer2/pants_officer2_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer2_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer2/pants_officer2_blood2.jpg
	{
		map textures/models/human/germanmaps/officer2/pants_officer2_blood2.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood1.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood2.jpg
		rgbGen lightingSpherical
	}
}

ss_smock_officer_cpt_blood1
{
	qer_editorimage textures/models/human/ss/smock_officer_cpt_blood1.jpg
	cull none
	{
		map textures/models/human/ss/smock_officer_cpt_blood1.jpg
		rgbGen lightingSpherical
	}
}

ss_smock_officer_cpt_blood2
{
	qer_editorimage textures/models/human/ss/smock_officer_cpt_blood2.jpg
	cull none
	{
		map textures/models/human/ss/smock_officer_cpt_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_tan_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_tan_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_private_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_private_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood2.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_private_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood1.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_private_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAKtrenchcoat_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAKtrenchcoat_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood2.jpg
		rgbGen lightingSpherical
	}
}

WpantsDAK_blood1
{
	qer_editorimage textures/models/human/DAK_new/WPantsDAK_blood1.jpg
	{
		map textures/models/human/DAK_new/WPantsDAK_blood1.jpg
		rgbGen lightingSpherical
	}
}

WpantsDAK_blood2
{
	qer_editorimage textures/models/human/DAK_new/WPantsDAK_blood2.jpg
	{
		map textures/models/human/DAK_new/WPantsDAK_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_green_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_green_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_nco_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_nco_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood2.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_nco_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood1.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_nco_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/officerpants_blood1.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/officerpants_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/officerpants_blood2.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/officerpants_blood2.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood1.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood2.jpg
		rgbGen lightingSpherical
	}
}

pants_dot_ss_blood1
{
	qer_editorimage textures/models/human/ss/pants_dot_ss_blood1.jpg				
	cull none
	{
		map textures/models/human/ss/pants_dot_ss_blood1.jpg
		rgbGen lightingSpherical
	}
}

pants_dot_ss_blood2
{
	qer_editorimage textures/models/human/ss/pants_dot_ss_blood2.jpg				
	cull none
	{
		map textures/models/human/ss/pants_dot_ss_blood2.jpg
		rgbGen lightingSpherical
	}
}

tunic_feldgrau_ss_blood1
{
	qer_editorimage textures/models/human/ss/tunic_feldgrau_ss_blood1.jpg
	cull none
	{
		map textures/models/human/ss/tunic_feldgrau_ss_blood1.jpg
		rgbGen lightingSpherical
	}
}

tunic_feldgrau_ss_blood2
{
	qer_editorimage textures/models/human/ss/tunic_feldgrau_ss_blood2.jpg
	cull none
	{
		map textures/models/human/ss/tunic_feldgrau_ss_blood2.jpg
		rgbGen lightingSpherical
	}
}

pshutze_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_pants_blood1.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

pshutze_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_pants_blood2.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood1.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood2.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_blood1
{
	qer_editorimage textures/models/human/ss/panzerwrap_blood1.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_blood1.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_blood2
{
	qer_editorimage textures/models/human/ss/panzerwrap_blood2.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_blood2.jpg
		rgbGen lightingSpherical
	}
}

panzerpants_blood1
{
	qer_editorimage textures/models/human/ss/panzerpants_black_blood1.jpg
	cull none
	{
		map textures/models/human/ss/panzerpants_black_blood1.jpg
		rgbGen lightingSpherical
	}
}

panzerpants_blood2
{
	qer_editorimage textures/models/human/ss/panzerpants_black_blood2.jpg
	cull none
	{
		map textures/models/human/ss/panzerpants_black_blood2.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_dot_nco_blood1
{
	qer_editorimage textures/models/human/ss/panzerwrap_dot_nco_blood1.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_dot_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_dot_nco_blood2
{
	qer_editorimage textures/models/human/ss/panzerwrap_dot_nco_blood2.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_dot_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_nco_blood1
{
	qer_editorimage textures/models/human/ss/panzerwrap_nco_blood1.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_nco_blood1.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_nco_blood2
{
	qer_editorimage textures/models/human/ss/panzerwrap_nco_blood2.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_nco_blood2.jpg
		rgbGen lightingSpherical
	}
}

sspanzerpants_dot_blood1
{
	qer_editorimage textures/models/human/ss/sspanzerpants_dot_blood1.jpg
	cull none
	{
		map textures/models/human/ss/sspanzerpants_dot_blood1.jpg
		rgbGen lightingSpherical
	}
}

sspanzerpants_dot_blood2
{
	qer_editorimage textures/models/human/ss/sspanzerpants_dot_blood2.jpg
	cull none
	{
		map textures/models/human/ss/sspanzerpants_dot_blood2.jpg
		rgbGen lightingSpherical
	}
}

sspanzer_ledermantel_blood1
{
	qer_editorimage textures/common/reflection1_blood1.jpg
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

sspanzer_ledermantel_blood2
{
	qer_editorimage textures/common/reflection1_blood2.jpg
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

sentry_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/pants_sentry_blood1.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/pants_sentry_blood1.jpg
		rgbGen lightingSpherical
	}
}

sentry_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/pants_sentry_blood2.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/pants_sentry_blood2.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_blood1
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood1.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood1.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_blood2
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood2.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood2.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_c_blood1
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood1.jpg
	cull none
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood1.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_c_blood2
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood2.jpg
	cull none
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood2.jpg
		rgbGen lightingSpherical
	}
}

generalcoat_blood1
{
	qer_editorimage textures/models/human/ssoff/Elite_officer_blood1.jpg
	{
		map textures/models/human/ssoff/Elite_officer_blood1.jpg
		rgbGen lightingSpherical
	}
}

generalcoat_blood2
{
	qer_editorimage textures/models/human/ssoff/Elite_officer_blood2.jpg
	{
		map textures/models/human/ssoff/Elite_officer_blood2.jpg
		rgbGen lightingSpherical
	}
}

gestapo_ledermantel_blood1
{
	qer_editorimage textures/common/reflection1_blood1.jpg
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/common/reflection1_blood1.jpg
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

gestapo_ledermantel_blood2
{
	qer_editorimage textures/common/reflection1_blood2.jpg
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/common/reflection1_blood2.jpg
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

worker_shirt_blood1
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_shirt_blood1.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_shirt_blood1.jpg
		rgbGen lightingSpherical
	}
}

worker_shirt_blood2
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_shirt_blood2.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_shirt_blood2.jpg
		rgbGen lightingSpherical
	}
}

worker_pants_blood1
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_pants_blood1.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

worker_pants_blood2
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_pants_blood2.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood1.jpg
	{
		map textures/models/human/usmaps/airborne/air_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood2.jpg
	{
		map textures/models/human/usmaps/airborne/air_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_cull_blood1
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood1.jpg
	cull none
	{
		map textures/models/human/usmaps/airborne/air_coat_blood1.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_cull_blood2
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood2.jpg
	cull none
	{
		map textures/models/human/usmaps/airborne/air_coat_blood2.jpg
		rgbGen lightingSpherical
	}
}

jeff_c_skin2
{
	qer_editorimage textures/models/human/faces/jeff_c_skin2.jpg
	
	{
		map textures/models/human/faces/jeff_c_skin2.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_Pants_blood1
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood1.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood1.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_Pants_blood2
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood2.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood2.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_tunic_blood1
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood1.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood1.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_tunic_blood2
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood2.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood2.jpg
		rgbGen lightingSpherical
	}
}

uk_head_pt_2_skin2
{
	qer_editorimage textures/models/human/faces/uk_pt_2_skin2.jpg
	{
		map textures/models/human/faces/uk_pt_2_skin2.jpg
		rgbGen lightingSpherical
	}
}

pt_hands_skin2
{
	qer_editorimage textures/models/human/pt_hands_skin2.jpg
	{
		map textures/models/human/pt_hands_skin2.jpg
		rgbGen lightingSpherical
	}
}

assaultvest_captain_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/av_captain_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/av_captain_blood1.jpg
		rgbGen lightingSpherical
	}
}

assaultvest_captain_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/av_captain_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/av_captain_blood2.jpg
		rgbGen lightingSpherical
	}
}

HBTpants_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_blood1.jpg
		rgbGen lightingSpherical
	}
}

HBTpants_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_blood2.jpg
		rgbGen lightingSpherical
	}
}

ranger_jacket2_blood1
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket2_blood1.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket2_blood1.jpg
		rgbGen lightingSpherical
	}
}

ranger_jacket2_blood2
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket2_blood2.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket2_blood2.jpg
		rgbGen lightingSpherical
	}
}

paul_dirty_skin2
{
	qer_editorimage textures/models/human/faces/paul_dirty_skin2.jpg
	
	{
		map textures/models/human/faces/paul_dirty_skin2.jpg
		rgbGen lightingSpherical
	}
}
