// HZM coop [2026-09-25] VEHICLE HEADLIGHTS (Phase H) - GENERATED by docs/tools/gen_coop_headlights.py;
// edit the generator, never this file. Both names exist ONLY here (TRAPS T6: one name, one coop file).
// Drawn only by cgame's CG_CoopHeadlights (openmohaa-hzm/code/cgame/cg_view.c), gl2 only, never on Omaha.

// The lamp glow. deformVertexes lightglow = the retail corona recipe (billboard + pull toward the eye), which needs
// renderer_opengl2's Phase R restore; cgame will not draw this while r_hzmLightGlow is off. rgbGen entity: cgame
// sets the per-viewer intensity (it fades to 0 as you move to the side of the vehicle). Own texture - the HD FX
// pack's corona_util is left alone, because every .spr is sized from its image (vet F19).
coop_headlamp_glow
{
	qer_editorimage textures/coop_fx/headlamp_glow.tga
	deformVertexes lightglow
	cull none
	nopicmip
	{
		clampmap textures/coop_fx/headlamp_glow.tga
		blendFunc GL_ONE GL_ONE
		rgbGen entity
	}
}

// The fog beam. rgbGen dot: rgb = (N.V)^2 * 1.2, so the cone's silhouette is dark and its face is lit - the soft
// volumetric edge, identical on gl1 and gl2 (Phase R2 ports gl1's RGB write). A single-bundle, deform-free dot stage
// would collapse into gl2's LIGHTALL and draw flat; Phase R2's CollapseStagesToGLSL skip keeps it generic.
// alphaGen entity + GL_SRC_ALPHA GL_ONE: additive, scaled by cgame's per-viewer fade.
// qer_hzmSoftEdge 32 (headlight S3b): renderer_opengl2 fades the beam out within 32 u of whatever is behind it (a soft
// particle's depth fade), so it never ends in a hard line on the ground, a wall or a soldier. Every renderer that does
// not know it skips it with the other qer* editor keywords.
coop_headbeam
{
	qer_editorimage textures/coop_fx/headbeam.tga
	qer_hzmSoftEdge 32
	cull none
	nopicmip
	{
		clampmap textures/coop_fx/headbeam.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen dot 0 1.2
		alphaGen entity
	}
}

// The lamp lens flare (Phase S2). NOT a model: renderer_opengl2 draws it (tr_hzm_spot_rb.c RB_HZM_SpotFlares) as a
// screen-space sprite in the scene, before the tonemap, for each flare cgame sends while r_hzmFlares resolves on.
// The renderer looks the name up in CreateExternalShaders and forces depth test off, no fog colour adjust and no
// global fog on it; occlusion is measured separately with GPU occlusion queries. rgbGen vertex: the renderer writes
// the colour (class tint x intensity x visibility x fog). If this shader is missing (an older pk3) the renderer
// draws no flares at all rather than a white square.
hzmLampFlare
{
	qer_editorimage textures/coop_fx/lampflare.tga
	nopicmip
	nomipmaps
	cull none
	{
		clampmap textures/coop_fx/lampflare.tga
		blendFunc GL_ONE GL_ONE
		rgbGen vertex
		nofog
	}
}
