// HZM coop - GORE TIER 1e (extreme explosion-death gib skins). GENERATED by
// scratchpad/gen_gore3_skins.py - do not hand-edit, re-run the generator.
// Skin index 3, applied by Sentient::CoopGoreTryGibSkins (fgame) when an AI
// dies to an explosion (native explosive MOD / projectile direct impact /
// script gore_gibmark). Every _blood3 block is the tier-1 heavy block (a
// retail-shader clone, cull/blend preserved) retargeted at a composite whose
// blood stays in the mod's dark #150200 arterial family (user color caps:
// cloth HOT <= RGB(38,4,1), skin MID <= RGB(30,4,1)). Names + texture paths
// exist ONLY in the coop pk3 (shader-isolation rule, bug-922).

ranger_pants_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_pantsboots_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_pantsboots_blood3.jpg
		rgbGen lightingSpherical
	}
}

army_jacket_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/army_jacket_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/army_jacket_blood3.jpg
		rgbGen lightingSpherical
	}
}

paul_dirty_blood3
{
	qer_editorimage textures/models/human/faces/paul_dirty_blood3.jpg
	
	{
		map textures/models/human/faces/paul_dirty_blood3.jpg
		rgbGen lightingSpherical
	}
}

handsnew_blood3
{
	qer_editorimage textures/models/human/handsnew_blood3.jpg
	{
		map textures/models/human/handsnew_blood3.jpg
		rgbGen lightingSpherical
	}
}

army_pantsgreen_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/army_pantsgreen_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/army_pantsgreen_blood3.jpg
		rgbGen lightingSpherical
	}
}

assaultvest_captain_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/av_captain_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/av_captain_blood3.jpg
		rgbGen lightingSpherical
	}
}

HBTpants_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/HBTpants_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/HBTpants_blood3.jpg
		rgbGen lightingSpherical
	}
}

ranger_jacket2_blood3
{
	qer_editorimage textures/models/human/usmaps/ranger/ranger_jacket2_blood3.jpg
	{
		map textures/models/human/usmaps/ranger/ranger_jacket2_blood3.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_Pants_blood3
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood3.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_Pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

Sc_AL_US_Inf_tunic_blood3
{
	qer_editorimage textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood3.jpg
	{
		map textures/models/human/usmaintt/Sc_AL_US_Inf_tunic_blood3.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_blood3
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood3.jpg
	{
		map textures/models/human/usmaps/airborne/air_coat_blood3.jpg
		rgbGen lightingSpherical
	}
}

airborne_pants_blood3
{
	qer_editorimage textures/models/human/usmaps/airborne/air_pants_blood3.jpg
	{
		map textures/models/human/usmaps/airborne/air_pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

airborne_top_cull_blood3
{
	qer_editorimage textures/models/human/usmaps/airborne/air_coat_blood3.jpg
	cull none
	{
		map textures/models/human/usmaps/airborne/air_coat_blood3.jpg
		rgbGen lightingSpherical
	}
}

brownpants_blood3
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood3.jpg
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood3.jpg
		rgbGen lightingSpherical
	}
}

cull_brownpants_blood3
{
	qer_editorimage textures/models/human/frenchmaps/resistance/brownpants_blood3.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/brownpants_blood3.jpg
		rgbGen lightingSpherical
	}
}

browncoat_blood3
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood3.jpg
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood3.jpg
		rgbGen lightingSpherical
	}
}

cull_browncoat_blood3
{
	qer_editorimage textures/models/human/frenchmaps/resistance/browncoat_blood3.jpg
	cull none
	{
		map textures/models/human/frenchmaps/resistance/browncoat_blood3.jpg
		rgbGen lightingSpherical
	}
}

jeff_c_blood3
{
	qer_editorimage textures/models/human/faces/jeff_c_blood3.jpg
	
	{
		map textures/models/human/faces/jeff_c_blood3.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_blood3
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood3.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood3.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_pants_blood3
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_pants_blood3.jpg
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

uk_pt_top_cull_blood3
{
	qer_editorimage textures/models/human/uk_paratrooper/uk_air_pt_coat_blood3.jpg
	cull none
	{
		map textures/models/human/uk_paratrooper/uk_air_pt_coat_blood3.jpg
		rgbGen lightingSpherical
	}
}

uk_head_pt_2_blood3
{
	qer_editorimage textures/models/human/faces/uk_pt_2_blood3.jpg
	{
		map textures/models/human/faces/uk_pt_2_blood3.jpg
		rgbGen lightingSpherical
	}
}

pt_hands_blood3
{
	qer_editorimage textures/models/human/pt_hands_blood3.jpg
	{
		map textures/models/human/pt_hands_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_green_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_green_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_nco_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood3.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_nco_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicnco_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicnco_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAKtrenchcoat_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKtrenchcoat_blood3.jpg
		rgbGen lightingSpherical
	}
}

WpantsDAK_blood3
{
	qer_editorimage textures/models/human/DAK_new/WPantsDAK_blood3.jpg
	{
		map textures/models/human/DAK_new/WPantsDAK_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/officerpants_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/officerpants_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_officer_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicofficer_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicofficer_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_pants_tan_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/DAKpants_tan_blood3.jpg
		rgbGen lightingSpherical
	}
}

DAK_private_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood3.jpg
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood3.jpg
		rgbGen lightingSpherical
	}
}

c_DAK_private_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/afrikakorps/tunicprivate_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/afrikakorps/tunicprivate_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer2_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer2/pants_officer2_blood3.jpg
	{
		map textures/models/human/germanmaps/officer2/pants_officer2_blood3.jpg
		rgbGen lightingSpherical
	}
}

generalcoat_blood3
{
	qer_editorimage textures/models/human/ssoff/Elite_officer_blood3.jpg
	{
		map textures/models/human/ssoff/Elite_officer_blood3.jpg
		rgbGen lightingSpherical
	}
}

// HZM bug-936b: regenerated multi-stage sheen material (see facewrap_blood3 note)
gestapo_ledermantel_blood3
{
	qer_editorimage textures/coop_gore3/gestapomantel_blood3.tga
	{
		map textures/common/reflection1.tga
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/coop_gore3/gestapomantel_blood3.tga
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

sentry_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/pants_sentry_blood3.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/pants_sentry_blood3.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood3.jpg
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood3.jpg
		rgbGen lightingSpherical
	}
}

sentry_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/elite_sentry/tunic_sentry_blood3.jpg
		rgbGen lightingSpherical
	}
}

worker_shirt_blood3
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_shirt_blood3.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_shirt_blood3.jpg
		rgbGen lightingSpherical
	}
}

worker_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/german_worker/worker_pants_blood3.jpg
	{
		map textures/models/human/germanmaps/german_worker/worker_pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

pants_dot_ss_blood3
{
	qer_editorimage textures/models/human/ss/pants_dot_ss_blood3.jpg				
	cull none
	{
		map textures/models/human/ss/pants_dot_ss_blood3.jpg
		rgbGen lightingSpherical
	}
}

tunic_feldgrau_ss_blood3
{
	qer_editorimage textures/models/human/ss/tunic_feldgrau_ss_blood3.jpg
	cull none
	{
		map textures/models/human/ss/tunic_feldgrau_ss_blood3.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_blood3
{
	qer_editorimage textures/models/human/ss/panzerwrap_blood3.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_blood3.jpg
		rgbGen lightingSpherical
	}
}

panzerpants_blood3
{
	qer_editorimage textures/models/human/ss/panzerpants_black_blood3.jpg
	cull none
	{
		map textures/models/human/ss/panzerpants_black_blood3.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_dot_nco_blood3
{
	qer_editorimage textures/models/human/ss/panzerwrap_dot_nco_blood3.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_dot_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

sspanzerwrap_nco_blood3
{
	qer_editorimage textures/models/human/ss/panzerwrap_nco_blood3.jpg
	cull none
	{
		map textures/models/human/ss/panzerwrap_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

sspanzerpants_dot_blood3
{
	qer_editorimage textures/models/human/ss/sspanzerpants_dot_blood3.jpg
	cull none
	{
		map textures/models/human/ss/sspanzerpants_dot_blood3.jpg
		rgbGen lightingSpherical
	}
}

pshutze_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_pants_blood3.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood3.jpg
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood3.jpg
		rgbGen lightingSpherical
	}
}

pshutze_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/panzershutze/pshutze_tunic_blood3.jpg
		rgbGen lightingSpherical
	}
}

// HZM bug-936b: regenerated multi-stage sheen material (see facewrap_blood3 note)
sspanzer_ledermantel_blood3
{
	qer_editorimage textures/coop_gore3/tc_coat2_blood3.tga
	{
		map textures/common/reflection1.tga
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/coop_gore3/tc_coat2_blood3.tga
		rgbGen lightingSpherical
		blendFunc GL_ONE_MINUS_SRC_ALPHA GL_SRC_ALPHA
	}
}

shutzshirt_nco_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood3.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_nco_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood3.jpg
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzpants_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

cull_shutzshirt_nco_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen_nco/shutzshirt_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood3.jpg
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer2_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer2/tunic_officer2_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer2/tunic_officer2_blood3.jpg
		rgbGen lightingSpherical
	}
}

ss_smock_officer_cpt_blood3
{
	qer_editorimage textures/models/human/ss/smock_officer_cpt_blood3.jpg
	cull none
	{
		map textures/models/human/ss/smock_officer_cpt_blood3.jpg
		rgbGen lightingSpherical
	}
}

shutzpants_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzpants_blood3.jpg
	{
		map textures/models/human/germanmaps/shutzen/shutzpants_blood3.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood3.jpg
	
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood3.jpg
		rgbGen lightingSpherical
	}
}

shutzshirt_cull_blood3
{
	qer_editorimage textures/models/human/germanmaps/shutzen/shutzshirt_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/shutzen/shutzshirt_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood3.jpg
	{
		map textures/models/human/germanmaps/wehrmact/wehrmact_pants_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet_blood3
{
	qer_editorimage textures/models/human/heer/wh_nco_vet_blood3.jpg
	{
		map textures/models/human/heer/wh_nco_vet_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_pants_camo2_blood3
{
	qer_editorimage textures/models/human/heer/wh_pants_camo2_blood3.jpg
	{
		map textures/models/human/heer/wh_pants_camo2_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_vet2_blood3
{
	qer_editorimage textures/models/human/heer/wh_nco_vet2_blood3.jpg
	{
		map textures/models/human/heer/wh_nco_vet2_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_nco_blood3
{
	qer_editorimage textures/models/human/heer/wh_nco_blood3.jpg
	{
		map textures/models/human/heer/wh_nco_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmact_pants_fgrey_blood3
{
	qer_editorimage textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood3.jpg
	{
		map textures/models/human/germanmaps/wehrmact/Wpantsfgrey_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_vet_blood3
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_vet_blood3.jpg
	{
		map textures/models/human/heer/wh_gefreiter_vet_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood3.jpg
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer_pants_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer/pants_officer_blood3.jpg
	{
		map textures/models/human/germanmaps/officer/pants_officer_blood3.jpg
		rgbGen lightingSpherical
	}
}

officer_tunic_c_blood3
{
	qer_editorimage textures/models/human/germanmaps/officer/tunic_officer_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/officer/tunic_officer_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_soldat_blood3
{
	cull none
	qer_editorimage textures/models/human/heer/wh_soldat_blood3.tga
	{
		map textures/models/human/heer/wh_soldat_blood3.tga
		alphaFunc GE128
		depthWrite
		rgbGen lightingSpherical
	}
}

heer_pants_late_blood3
{
	qer_editorimage textures/models/human/heer/WPantsfgrey_alt_blood3.jpg				
	{
		map textures/models/human/heer/WPantsfgrey_alt_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_sniper_blood3
{
	qer_editorimage textures/models/human/heer/wh_sniper_vet_blood3.jpg
	{
		map textures/models/human/heer/wh_sniper_vet_blood3.jpg
		rgbGen lightingSpherical
	}
}

wehrmacht_alt_soldat_blood3
{
	cull none
	qer_editorimage textures/models/human/heer/wh_alt_soldat_blood3.tga		
	{
		map textures/models/human/heer/wh_alt_soldat_blood3.tga
		alphaFunc GE128
		depthWrite
		rgbGen lightingSpherical
	}
}

wehrmacht_gefreiter_blood3
{
	qer_editorimage textures/models/human/heer/wh_gefreiter_blood3.jpg
	{
		map textures/models/human/heer/wh_gefreiter_blood3.jpg
		rgbGen lightingSpherical
	}
}

wintertop1_blood3
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/wintertop1_blood3.jpg
	{
		map textures/models/human/germanmaps/wintertroops/wintertop1_blood3.jpg
		rgbGen lightingSpherical
	}
}

cull_winterpants1_blood3
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood3.jpg
	cull none
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood3.jpg
		rgbGen lightingSpherical
	}
}

winterpants1_blood3
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/winterpants1_blood3.jpg
	{
		map textures/models/human/germanmaps/wintertroops/winterpants1_blood3.jpg
		rgbGen lightingSpherical
	}
}

knitgloves1_blood3
{
	qer_editorimage textures/models/human/germanmaps/wintertroops/knitgloves1_blood3.jpg
	{
		map textures/models/human/germanmaps/wintertroops/knitgloves1_blood3.jpg
		rgbGen lightingSpherical
	}
}

mantel_blood3
{
	qer_editorimage textures/models/human/ger_winter/trenchcoat_blood3.jpg
	{
		map textures/models/human/ger_winter/trenchcoat_blood3.jpg
		rgbGen lightingSpherical
	}
}

bensonazi_blood3
{
	qer_editorimage textures/models/human/faces/Bensonazi_blood3.jpg
	
	{
		map textures/models/human/faces/Bensonazi_blood3.jpg
		rgbGen lightingSpherical
	}
}

bignose_blood3
{
	qer_editorimage textures/models/human/faces/bignose_blood3.jpg
	{
		map textures/models/human/faces/bignose_blood3.jpg
		rgbGen lightingSpherical
	}
}

dolf_blood3
{
	qer_editorimage textures/models/human/faces/dolf_blood3.jpg
	{
		map textures/models/human/faces/dolf_blood3.jpg
		rgbGen lightingSpherical
	}
}

hans_blood3
{
	qer_editorimage textures/models/human/faces/hans_blood3.jpg
	
	{
		map textures/models/human/faces/hans_blood3.jpg
		rgbGen lightingSpherical
	}
}

gunter_blood3
{
	qer_editorimage textures/models/human/faces/gunter_blood3.jpg
	
	{
		map textures/models/human/faces/gunter_blood3.jpg
		rgbGen lightingSpherical
	}
}

gustav_blood3
{
	qer_editorimage textures/models/human/faces/gustav_blood3.jpg
	
	{
		map textures/models/human/faces/gustav_blood3.jpg
		rgbGen lightingSpherical
	}
}

hopper_blood3
{
	qer_editorimage textures/models/human/faces/hopper_blood3.jpg
	{
		map textures/models/human/faces/hopper_blood3.jpg
		rgbGen lightingSpherical
	}
}

old_dog_blood3
{
	qer_editorimage textures/models/human/faces/old_dog_blood3.jpg
	{
		map textures/models/human/faces/old_dog_blood3.jpg
		rgbGen lightingSpherical
	}
}

roml_blood3
{
	qer_editorimage textures/models/human/faces/roml_blood3.jpg
	
	{
		map textures/models/human/faces/roml_blood3.jpg
		rgbGen lightingSpherical
	}
}

maxwell_blood3
{
	qer_editorimage textures/models/human/faces/maxwell_blood3.jpg
	
	{
		map textures/models/human/faces/maxwell_blood3.jpg
		rgbGen lightingSpherical
	}
}

dominik_blood3
{
	qer_editorimage textures/models/human/faces/dominik_blood3.jpg
	
	{
		map textures/models/human/faces/dominik_blood3.jpg
		rgbGen lightingSpherical
	}
}

wolfgang_blood3
{
	qer_editorimage textures/models/human/faces/wolfgang_blood3.jpg
	
	{
		map textures/models/human/faces/wolfgang_blood3.jpg
		rgbGen lightingSpherical
	}
}

// HZM bug-936b: REGENERATED - the generator blood-composited the env-REFLECTION map of this
// multi-stage sheen material (rendered as a solid white blob). This def mirrors the ORIGINAL stage
// structure with blood composited on the real diffuse texture only, alpha preserved for the blendfunc.
facewrap_blood3
{
	qer_editorimage textures/coop_gore3/DAkfacewrap_blood3.tga
	{
		map textures/common/reflection1.tga
		rgbGen lightingSpherical
		tcgen environmentmodel
	}
	{
		map textures/coop_gore3/DAkfacewrap_blood3.tga
		rgbGen lightingSpherical
		blendfunc gl_one_minus_src_alpha gl_src_alpha 
	}
}

us_north_blood3
{
	qer_editorimage textures/models/human/faces/us_north_blood3.jpg
	
	{
		map textures/models/human/faces/us_north_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_thomas_blood3
{
	qer_editorimage textures/models/human/faces/us_thomas_blood3.jpg
	
	{
		map textures/models/human/faces/us_thomas_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_z_blood3
{
	qer_editorimage textures/models/human/faces/us_z_blood3.jpg
	
	{
		map textures/models/human/faces/us_z_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_j_blood3
{
	qer_editorimage textures/models/human/faces/us_j_blood3.jpg
	
	{
		map textures/models/human/faces/us_j_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_senn_blood3
{
	qer_editorimage textures/models/human/faces/us_senn_blood3.jpg
	
	{
		map textures/models/human/faces/us_senn_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_powzer_blood3
{
	qer_editorimage textures/models/human/faces/us_powzer_blood3.jpg
	
	{
		map textures/models/human/faces/us_powzer_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_mike_blood3
{
	qer_editorimage textures/models/human/faces/us_mike_blood3.jpg
	
	{
		map textures/models/human/faces/us_mike_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_chance_blood3
{
	qer_editorimage textures/models/human/faces/us_chance_blood3.jpg
	
	{
		map textures/models/human/faces/us_chance_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_bob_blood3
{
	qer_editorimage textures/models/human/faces/us_bob_blood3.jpg
	
	{
		map textures/models/human/faces/us_bob_blood3.jpg
		rgbGen lightingSpherical
	}
}

us_dave_blood3
{
	qer_editorimage textures/models/human/faces/us_dave_blood3.jpg
	
	{
		map textures/models/human/faces/us_dave_blood3.jpg
		rgbGen lightingSpherical
	}
}

slick_blood3
{
	qer_editorimage textures/models/human/faces/slick_blood3.jpg
	
	{
		map textures/models/human/faces/slick_blood3.jpg
		rgbGen lightingSpherical
	}
}

srg_blood3
{
	qer_editorimage textures/models/human/faces/srg_blood3.jpg
	cull none	
	{
		map textures/models/human/faces/srg_blood3.jpg
		rgbGen lightingSpherical
	}
}

tom_blood3
{
	qer_editorimage textures/models/human/faces/tom_blood3.jpg
	
	{
		map textures/models/human/faces/tom_blood3.jpg
		rgbGen lightingSpherical
	}
}
