// HZM coop [2026-09-01, bug-2241] FINISHES FOR MAGAZINES THAT WEAR THEIR OWN SHEET.
// GENERATED by docs/tools/gen_clip_art.py - do not hand-edit, re-run the generator.
//
// gen_clip_skins.py hands a magazine whatever finish shader the gun's own variant TIK uses
// for the surface wearing that texture. That works for every magazine painted from a sheet
// the gun body also wears. These five are painted from a sheet the gun never uses - the
// shared m1clip sheet, barclip, mauserammo - so no finish existed for them at all.
//
// The tint table and the shader emitter are IMPORTED from gen_skins.py, so if the finish
// palette is retuned these follow it. Gold, chrome and blued are pure stages and need no
// art; only bloody and the three camos are baked, by bake_skins.py's own functions.
//
// The _clip suffix keeps these clear of the gun's coop_skin_<gun>_<finish>[_N] blocks,
// which are indexed by the GUN's surface order and must not be disturbed.

coop_skin_enfield_gold_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 1.00 0.78 0.30
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.40 0.31 0.12
	}
}

coop_skin_enfield_chrome_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.88 0.92 0.98
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.55 0.58 0.64
	}
}

coop_skin_enfield_blued_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.44 0.48 0.64
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.10 0.12 0.20
	}
}

coop_skin_enfield_bloody_clip
{
	qer_editorimage textures/coop_skins/enfield/m1clip_bloody.jpg
	{
		map textures/coop_skins/enfield/m1clip_bloody.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_enfield_camo_woodland_clip
{
	qer_editorimage textures/coop_skins/enfield/m1clip_camo_woodland.jpg
	{
		map textures/coop_skins/enfield/m1clip_camo_woodland.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_enfield_camo_winter_clip
{
	qer_editorimage textures/coop_skins/enfield/m1clip_camo_winter.jpg
	{
		map textures/coop_skins/enfield/m1clip_camo_winter.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_enfield_camo_desert_clip
{
	qer_editorimage textures/coop_skins/enfield/m1clip_camo_desert.jpg
	{
		map textures/coop_skins/enfield/m1clip_camo_desert.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_springfield_gold_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 1.00 0.78 0.30
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.40 0.31 0.12
	}
}

coop_skin_springfield_chrome_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.88 0.92 0.98
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.55 0.58 0.64
	}
}

coop_skin_springfield_blued_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.44 0.48 0.64
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.10 0.12 0.20
	}
}

coop_skin_springfield_bloody_clip
{
	qer_editorimage textures/coop_skins/springfield/m1clip_bloody.jpg
	{
		map textures/coop_skins/springfield/m1clip_bloody.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_springfield_camo_woodland_clip
{
	qer_editorimage textures/coop_skins/springfield/m1clip_camo_woodland.jpg
	{
		map textures/coop_skins/springfield/m1clip_camo_woodland.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_springfield_camo_winter_clip
{
	qer_editorimage textures/coop_skins/springfield/m1clip_camo_winter.jpg
	{
		map textures/coop_skins/springfield/m1clip_camo_winter.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_springfield_camo_desert_clip
{
	qer_editorimage textures/coop_skins/springfield/m1clip_camo_desert.jpg
	{
		map textures/coop_skins/springfield/m1clip_camo_desert.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_it_w_carcano_gold_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 1.00 0.78 0.30
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.40 0.31 0.12
	}
}

coop_skin_it_w_carcano_chrome_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.88 0.92 0.98
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.55 0.58 0.64
	}
}

coop_skin_it_w_carcano_blued_clip
{
	qer_editorimage textures/models/weapons/m1garand/m1clip.tga
	{
		map textures/models/weapons/m1garand/m1clip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.44 0.48 0.64
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.10 0.12 0.20
	}
}

coop_skin_it_w_carcano_bloody_clip
{
	qer_editorimage textures/coop_skins/it_w_carcano/m1clip_bloody.jpg
	{
		map textures/coop_skins/it_w_carcano/m1clip_bloody.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_it_w_carcano_camo_woodland_clip
{
	qer_editorimage textures/coop_skins/it_w_carcano/m1clip_camo_woodland.jpg
	{
		map textures/coop_skins/it_w_carcano/m1clip_camo_woodland.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_it_w_carcano_camo_winter_clip
{
	qer_editorimage textures/coop_skins/it_w_carcano/m1clip_camo_winter.jpg
	{
		map textures/coop_skins/it_w_carcano/m1clip_camo_winter.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_it_w_carcano_camo_desert_clip
{
	qer_editorimage textures/coop_skins/it_w_carcano/m1clip_camo_desert.jpg
	{
		map textures/coop_skins/it_w_carcano/m1clip_camo_desert.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_bar_gold_clip
{
	qer_editorimage textures/models/weapons/bar/barclip.tga
	{
		map textures/models/weapons/bar/barclip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 1.00 0.78 0.30
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.40 0.31 0.12
	}
}

coop_skin_bar_chrome_clip
{
	qer_editorimage textures/models/weapons/bar/barclip.tga
	{
		map textures/models/weapons/bar/barclip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.88 0.92 0.98
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.55 0.58 0.64
	}
}

coop_skin_bar_blued_clip
{
	qer_editorimage textures/models/weapons/bar/barclip.tga
	{
		map textures/models/weapons/bar/barclip.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.44 0.48 0.64
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.10 0.12 0.20
	}
}

coop_skin_bar_bloody_clip
{
	qer_editorimage textures/coop_skins/bar/barclip_bloody.jpg
	{
		map textures/coop_skins/bar/barclip_bloody.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_bar_camo_woodland_clip
{
	qer_editorimage textures/coop_skins/bar/barclip_camo_woodland.jpg
	{
		map textures/coop_skins/bar/barclip_camo_woodland.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_bar_camo_winter_clip
{
	qer_editorimage textures/coop_skins/bar/barclip_camo_winter.jpg
	{
		map textures/coop_skins/bar/barclip_camo_winter.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_bar_camo_desert_clip
{
	qer_editorimage textures/coop_skins/bar/barclip_camo_desert.jpg
	{
		map textures/coop_skins/bar/barclip_camo_desert.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_kar98_gold_clip
{
	qer_editorimage textures/models/weapons/kar98/mauserammo.tga
	{
		map textures/models/weapons/kar98/mauserammo.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 1.00 0.78 0.30
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.40 0.31 0.12
	}
}

coop_skin_kar98_chrome_clip
{
	qer_editorimage textures/models/weapons/kar98/mauserammo.tga
	{
		map textures/models/weapons/kar98/mauserammo.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.88 0.92 0.98
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.55 0.58 0.64
	}
}

coop_skin_kar98_blued_clip
{
	qer_editorimage textures/models/weapons/kar98/mauserammo.tga
	{
		map textures/models/weapons/kar98/mauserammo.tga
		rgbGen lightingSpherical
	}
	{
		map $whiteimage
		blendFunc GL_DST_COLOR GL_ZERO
		rgbGen const 0.44 0.48 0.64
	}
	{
		map textures/coop_skins/env_sheen.tga
		blendFunc add
		tcGen environment
		rgbGen const 0.10 0.12 0.20
	}
}

coop_skin_kar98_bloody_clip
{
	qer_editorimage textures/coop_skins/kar98/mauserammo_bloody.jpg
	{
		map textures/coop_skins/kar98/mauserammo_bloody.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_kar98_camo_woodland_clip
{
	qer_editorimage textures/coop_skins/kar98/mauserammo_camo_woodland.jpg
	{
		map textures/coop_skins/kar98/mauserammo_camo_woodland.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_kar98_camo_winter_clip
{
	qer_editorimage textures/coop_skins/kar98/mauserammo_camo_winter.jpg
	{
		map textures/coop_skins/kar98/mauserammo_camo_winter.jpg
		rgbGen lightingSpherical
	}
}

coop_skin_kar98_camo_desert_clip
{
	qer_editorimage textures/coop_skins/kar98/mauserammo_camo_desert.jpg
	{
		map textures/coop_skins/kar98/mauserammo_camo_desert.jpg
		rgbGen lightingSpherical
	}
}
