// HZM coop [user 2026-09-28] LOADING-SCREEN ART POOL - generated by
// docs/proposals/bt_loadscreens_2026-09-28/tools/la_ship.py. One shader per image; ui/loadart.txt picks one per
// load (the exe's UI_LoadArt_Begin) and ui/loadingbar.txt's hzm_loadart widget draws it (linkcvartoshader).
// Art: real in-engine captures of staged Allied-vs-Axis scenes, finished offline (aged-photo card). No text.

// AA - Battle in the Bocage (m3l2)
hzmLoadArt_aa1_bocage
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/aa1_bocage.jpg
	}
}

// AA - Destroyed Village (m5l2a)
hzmLoadArt_aa2_village
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/aa2_village.jpg
	}
}

// AA - Siegfried Forest (m6l1a)
hzmLoadArt_aa3_siegfried
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/aa3_siegfried.jpg
	}
}

// AA - The Rescue Mission, Arzew (m1l2a)
hzmLoadArt_aa4_arzew
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/aa4_arzew.jpg
	}
}

// SH - Bastogne (t2l1)
hzmLoadArt_sh1_bastogne
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/sh1_bastogne.jpg
	}
}

// BT - Kasserine Pass (e1l1)
hzmLoadArt_bt1_kasserine
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/bt1_kasserine.jpg
	}
}

// BT - Monte Cassino (e3l1)
hzmLoadArt_bt3_cassino
{
	nopicmip
	cull none
	force32bit
	surfaceparm nolightmap
	{
		clampMap textures/mohmenu/hzmload/bt3_cassino.jpg
	}
}
