// GENERATED by docs/tools/gen_glove_views.py - DO NOT HAND-EDIT
//
// First-person glove textures for the armory glove row (bug-2080). The 3P and 1P hands
// are different meshes with different UV layouts - shipped content shares ZERO hand
// shaders between them - so a 3P glove texture cannot be shown in first person. Each
// texture here is an existing 1P glove (already correct for the 1P UVs) recoloured to
// the mean colour of its 3P counterpart, so the same glove reads the same in both views.

textures/models/human/coop_glove_mittens_view
{
	qer_editorimage textures/models/human/coop_glove_mittens_view.tga
	{
		map textures/models/human/coop_glove_mittens_view.tga
		rgbGen lightingSpherical
	}
}

coop_glove_mittens_view
{
	qer_editorimage textures/models/human/coop_glove_mittens_view.tga
	{
		map textures/models/human/coop_glove_mittens_view.tga
		rgbGen lightingSpherical
	}
}

textures/models/human/coop_glove_seaman_view
{
	qer_editorimage textures/models/human/coop_glove_seaman_view.tga
	{
		map textures/models/human/coop_glove_seaman_view.tga
		rgbGen lightingSpherical
	}
}

coop_glove_seaman_view
{
	qer_editorimage textures/models/human/coop_glove_seaman_view.tga
	{
		map textures/models/human/coop_glove_seaman_view.tga
		rgbGen lightingSpherical
	}
}

textures/models/human/coop_glove_uswinter_view
{
	qer_editorimage textures/models/human/coop_glove_uswinter_view.tga
	{
		map textures/models/human/coop_glove_uswinter_view.tga
		rgbGen lightingSpherical
	}
}

coop_glove_uswinter_view
{
	qer_editorimage textures/models/human/coop_glove_uswinter_view.tga
	{
		map textures/models/human/coop_glove_uswinter_view.tga
		rgbGen lightingSpherical
	}
}
