// HZM coop [user 2026-09-06, bug-2508] THE DENSE SEA - shader for models/fx/coop_sea.tik (m3l1a).
// GENERATED by docs/tools/gen_coop_sea.py - do not hand-edit; edit the generator and re-run.
//
// A restatement of textures/misc_outside/deepbluesea as it ships in zz_coop_ocean.shader (the two
// retail stages, the bug-2507 lid: blendFunc blend + depthwrite + alphaGen entity so `alpha 0.6` on
// the entity works the same way) with the retail `flap` hinge replaced by two TRAVELLING waves. On
// the 64-vert patch a wave is under-sampled; on the coop_sea mesh (121.7 u rows) it is not.
//
// `deformVertexes wave <div> sin <base> <amp> <phase> <freq>` phases each vertex by (x+y+z)/div in
// entity space. The mesh is pre-rotated for yaw 225, so x+y = -sqrt(2)*(Y - oy): the wavelength
// along world Y is div/sqrt(2) = 2401 / 983 u and a positive freq moves the crests toward +Y = the beach.
// The per-vertex amplitude is the mesh's own normal length (0 on the seam row, 1 from 1200 u out),
// so nothing here needs to know where the seam is. Two deforms put this shader on the CPU deform
// path (tr_local.h:2846), where both are applied (tr_shade_calc.c:704-715); 1,617 verts, trivial.
//
// KILL SWITCH for the look: this file (the script switch is level.coop_seaMeshOn). To tune: amp is
// vertical units at full taper (summed 20.049), div = wavelength * 1.4142, freq = 1 / period.
// Keep the summed amplitude near the retail sheet's own +/-8.5 at the fleet (bug-2478) or the boats
// drown again. One name, one coop file (TRAPS T6). No lightmap stage: this is an entity.
coop_sea_deep
{
	qer_editorimage textures/misc_outside/ocean2.tga
	qer_keyword natural
	qer_keyword liquid
	qer_keyword ocean
	qer_trans .4
	surfaceparm trans
	surfaceparm water
	surfaceparm nolightmap
	cull none

	deformVertexes wave 3396 sin 0 14.145 0 0.16		// swell: lambda 2401 u = 61.0 m, T 6.25 s - the shore crest's own arrival period
	deformVertexes wave 1390 sin 0 5.904 0 0.25		// chop:  lambda  983 u = 25.0 m, T 4.00 s

	{
		nopicmip
		depthwrite
		map textures/misc_outside/oceandday1.tga
		blendFunc blend
		alphaGen entity
		rgbGen identityLighting
		tcMod scale 16 22
		tcMod scroll 0.01 .03
	nextbundle
		map textures/misc_outside/oceandday1.tga
		tcMod scale -16 22
		tcMod scroll 0.01 0.04
	}
	{
		nopicmip
		map textures/misc_outside/oceandday1.tga
		blendFunc add
		tcMod scale .2 .5
		tcMod scroll 0 .005
	nextbundle
		map textures/misc_outside/oceandday1.tga
		tcMod scale .2 .5
		tcMod scroll 0 .01
	}
}
