// GENERATED by docs/tools/gen_coop_surf.py [bug-2521] - do not hand-edit, regenerate.
//
// THE SURF ZONE'S MOVING CREST. models/fx/coop_surf.tik floats 6 u above the painted shore water
// and carries breakfoam.tga - the same band zz_coop_shoreline.shader stage 2 paints, in the same
// world place, because this mesh's t is authored with the sheet's own mapping (t = (y+2167)/1408).
// The sheet keeps painting the wash; this adds the relief.
//
// ONE deform, and it is inversesawtooth rather than sin on purpose. A broken bore is a steep face
// with a long tail, and a sawtooth's face collapses to one sample step so its slope is amp divided by
// the row spacing (20.0/39.4 = 0.507, about 26.9 degrees) instead of a sine's gentle k*a. It also runs
// 0..1 rather than -1..1, so this layer NEVER dips below its rest plane and stays clear of the
// sheet's own +/-3.97 u flap.
//
// NO depthwrite and an additive blend: this must never occlude the eight tuned stages underneath it.
// Kill switch: level.coop_surfMeshOn 0, or regenerate with --flat (amplitude 0, no shader edit).
coop_surf_bore
{
	qer_editorimage textures/coop_fx/breakfoam.tga
	qer_keyword natural
	qer_keyword liquid
	surfaceparm trans
	surfaceparm water
	surfaceparm nolightmap
	cull none

	deformVertexes wave 792.0 inversesawtooth 0 20.0 0 0.20		// bore: lambda 560 u = 14.2 m, T 5.0 s, 112 u/s up the beach

	{
		nopicmip
		map textures/coop_fx/breakfoam.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.30 0.06 0 0.08
		tcMod wavetrant sin 0 -0.06 0 0.08
	nextbundle
		map textures/coop_fx/surfcell.tga
	}

	// [bug-2524] THE BORE TRAIN. Stage 1 above is the authored break-line band and stays put.
	// This tiles the same texture ONCE PER GEOMETRIC BORE, so every crest carries foam and every
	// trough is clear water; before it, ~63% of this mesh's cross-shore span drew alpha 0 for
	// ever. breakfoam.tga's t=0 and t=1 rows are both alpha 0 and luminance 0, so it tiles with
	// no seam, and its 35% duty cycle becomes 35% foam / 65% clear per crest.
	// The T scale is the mesh's own deform phase gradient measured on the shipped geometry with
	// the yaw-215 pre-rotation and the sheet's z-ramp included: 2.4238 cycles per 1.0 t. This
	// stage's t-scale is POSITIVE, so shoreward is NEGATIVE scroll - the mirror of the shore
	// sheet's crest stage, from the same derivation.
	// alphaGen tCoord reads the RAW texcoord before every tcMod, so the scroll cannot drag it:
	// it kills the train at t 0.82 (y -1006) before the wet-sand strip, and costs no tcMod slot.
	// surfcell on bundle 1 is MANDATORY: the deform's phase is linear in position, so its crest
	// is a mathematically straight 15872 u line and nothing else can rag it.
	{
		nopicmip
		map textures/coop_fx/breakfoam.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen identity
		alphaGen tCoord 8.2 -1.8 0 1
		tcMod scale 1 2.4238
		tcMod scroll 0 -0.2000
	nextbundle
		map textures/coop_fx/surfcell.tga
	}

	// [user 2026-09-07, bug-2525] THE TROUGH SHADOW - 'is there no way to make the waves actually
	// more 3d?'. The geometry here is real; what is missing is that nothing on this beach is shaded
	// and nothing can be: every water shader is nolightmap, the map's sun sits at the exact zenith
	// so a crest and a trough take identical light, and deformVertexes never writes tess.normal, so
	// every orientation-based generator reads a stale straight-up normal and draws a vignette.
	// But the wave's shape is deterministic, so its light and dark is too - and since bug-2524 the
	// paint and the geometry travel at the same speed and spacing, so a painted shadow STAYS in the
	// trough instead of drifting through it. The stage above puts the highlight on the crest; this
	// puts the shadow in the trough, measured to be exactly half a period away from it. A highlight
	// alone is a stripe. A highlight with a shadow is a form. That pairing is the only shading this
	// water will ever have.
	// blendFunc blend pulls the water TOWARD the texture's dark colour in proportion to its alpha,
	// so it is a shadow rather than a smear; alphaGen tCoord kills it landward on the same knee the
	// foam uses, and reads the RAW texcoord so the scroll cannot drag it.
	// Kill switch: python docs/tools/gen_boreshade.py --flat, no shader edit.
	{
		nopicmip
		map textures/coop_fx/boreshade.tga
		blendFunc blend
		rgbGen identity
		alphaGen tCoord 8.2 -1.8 0 1
		tcMod scale 1 2.4238
		tcMod scroll 0 -0.2000
	}
}
