// GENERATED by docs/tools/gen_coop_surf.py [bug-2521] - do not hand-edit, regenerate.
//
// THE SURF ZONE'S MOVING CREST. models/fx/coop_surf.tik floats 6 u above the painted shore water
// and carries breakfoam.tga - the same band zz_coop_shoreline.shader stage 2 paints, in the same
// world place, because this mesh's t is authored with the sheet's own mapping (t = (y+2167)/1408).
// The sheet keeps painting the wash; this adds the relief.
//
// ONE deform, and it is inversesawtooth rather than sin on purpose. A broken bore is a steep face
// with a long tail, and a sawtooth's face collapses to one sample step so its slope is amp divided by
// the row spacing (6.0/39.4 = 0.152, about 8.7 degrees) instead of a sine's gentle k*a. It also runs
// 0..1 rather than -1..1, so this layer NEVER dips below its rest plane and stays clear of the
// sheet's own +/-3.97 u flap.
//
// NO depthwrite and an additive blend: this must never occlude the eight tuned stages underneath it.
// Kill switch: level.coop_surfMeshOn 0, or regenerate with --flat (amplitude 0, no shader edit).
coop_surf_bore
{
	qer_editorimage textures/coop_fx/breakfoam.tga
	qer_keyword natural
	qer_keyword liquid
	surfaceparm trans
	surfaceparm water
	surfaceparm nolightmap
	cull none

	deformVertexes wave 792.0 inversesawtooth 0 6.0 0 0.20		// bore: lambda 560 u = 14.2 m, T 5.0 s, 112 u/s up the beach

	{
		nopicmip
		map textures/coop_fx/breakfoam.tga
		blendFunc GL_SRC_ALPHA GL_ONE
		rgbGen wave sin 0.20 0.18 0 0.08
		tcMod scale 1 1
		tcMod wavetrant sin 0 -0.06 0 0.08
	nextbundle
		map textures/coop_fx/surfcell.tga
	}
}
